### ISSUE TITLE
verwirrende Zeitangabe über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#101]
Von: Veronika Schöll 
Auf BzB steht 4 std 30 - auf Zuugle 4.50 damit ist vielkeicht 4 1/2 std
gemeint - ist verwirrend.

https://www2.zuugle.at/tour?id=5743&city=bischofshofen

-- 

*Verein Bahn zum Berg*

*Zuuglest du schon, oder fährst du noch?*

ZVR: 1112324997

w: www.bahn-zum-berg.at / www.bahn-zum-berg.de

m: veronika.schoell@bahn-zum-berg.at

t: +436645345626

Attachments (1): https://zapier.com/engine/hydrate/11523678/.eJxNkVuTmkAUhP_LPEsKGBDwDRZQQAgu6O6YSlHDTUDlNoOglv89ZJNU5bVPn_6qup8gaWqa1TSi9zYDK6CCBShrQnGdZFGZghXkRZldQmEBkoHQ5jqQrP86cJzIw6UkLwBOkmaYI_6pnADZBcjL7JJGNb7-jsWU4qS4ziAyA84j7k8ErJ7gmhGCT39IgJMxt8wUCFOMeShLs_P_v9WPJ_jyqd66Sm2lDaEa-3b84Gh768qTTBMxHRtt-11vpjuz49V4uGzZRr5xD0_Y0FG6JFFVGNVRj5g1mjJr6gq2sXKzq3XbnjqT5uWO-qM03ODullVlqN4KteBHlvaOZjp9WkVOvlcnl3jGEIxhJB6obG3z5kCKKIgxQqfct3SnC4WlgZZjVXTlxLhY7UgidohtJQStySSaqNJwlEuXyR88vcjNfjds5Wa038XrQQ1xccTTNXI9rImP1HBxIj7CzkKxgkhb7eFnNWzCpVtN53cSmAdsmNUR9VCHZ15TtpwRFEhMAzshW017y4qSEWrdPTnmEd69Dz3qFZZ6NoM6EY2PyetM3S-myIDmLiv8gB_ymNWbgyMg-3YPyNuHetyHmuAHl7lMavPNhvAy50hrrfYN9qwwn_f2zM1b_Z3actcRz7LSt6o9gdfP1-sXc8bKXQ:1qXz6m:M4UpFKqWTH12P1y3SIjUUykVU6o/

**Comment by martinheppner** [comment]
4,5h have to be translated to 4 h 30 min (like on the result page)

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/93b12859-1362-495a-998a-bc1925e37823)

**Comment by FALBZB** [comment]
Still there may slightly be different duration displayed in both this section (ItineraryTourTimeLineContainer.js) and the TourDetailProperties.js part within the detailReworked.js (detail page)
