### ISSUE TITLE
Tourprofil Abstände über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#102]
Von: Veronika Schöll 
Zwischen den Angaben fehlt ein Abstand (außer bei max.Höhe)

-- 

*Verein Bahn zum Berg*

*Zuuglest du schon, oder fährst du noch?*

ZVR: 1112324997

w: www.bahn-zum-berg.at / www.bahn-zum-berg.de

m: veronika.schoell@bahn-zum-berg.at

t: +436645345626

Attachments (1): https://zapier.com/engine/hydrate/11523678/.eJxNklmPokAUhf9LPcuEffGNRVHUcldwMqkUayGySEE3YPzvzfTMJPN67znnS-65LxCURRMVDWr6KgJToIMJSAva4CKIUBqCqcBLKisL4gQELW3KvKVR_b3gOIkXZEWdABwEZTtG_JtyosBOQJxGjxAVOP8di5sGByQfQXQEZJ-4TiiYvkAeUYqTPyTAqZiTIzGORY6NZBaPyv99058v8K3ToX0PHQYaW_UpXjdUUk9hYOJ-Ycq6xDf7Xb06k8BHTulJO-J1et-ZVnEkt41bOYlHvRUnbnd-1a0fpN07bOydniG1qbK9JeVqoQ6uieOCT71nBmfiekBNttB4xzCKhhEsYb3ON0hRV3qGZ_uZpCwZ7iIt761h2tLpcEaOtSXJEcJq-EBqL-twjxbUuu1SLfMOaWZ8mgnlheCuKFJuPhaDT_i20PxWt50ysjZdF6xdxm7bWW5D5ri69VUzs3ceTRJkx6faHkjHRFyJNML3fq36plBcFZmcLYt1A8ucMx3WTh8pZ2x4YpczfOcOOzlPRIURBgTn0H26VZbrGnuA50dwcYjxkOGc4x2yD4vjeVBNdA1zpjNh55TLAw2H-tInUK_Uizs-glYPezhoZ2W8YmodhLsEr0s4dvW36uXGRjzLyj_uVQLev97vL31ixn8:1qXz6m:PqVWq6ihf2pygW_tDFoUu7abnDw/

**Comment by FALBZB** [comment]
@martinheppner  : i assume Veronika must be using her mobile, right ? maybe our testers should mention that

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/f19bb046-9b6e-453f-a0de-6e9bec181516)

**Comment by FALBZB** [comment]
will use the delivery of the detail page design work from externals to get this done

**Comment by FALBZB** [comment]
done
