### ISSUE TITLE
English : Umstiege über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#104]
Von: Veronika Schöll 
https://www2.zuugle.at/tour?id=5743&city=bischofshofen

auf English umgestellt - Umstiege ist nicht übersetzt, teilweise
überlappend

-- 

*Verein Bahn zum Berg*

*Zuuglest du schon, oder fährst du noch?*

ZVR: 1112324997

w: www.bahn-zum-berg.at / www.bahn-zum-berg.de

m: veronika.schoell@bahn-zum-berg.at

t: +436645345626

Attachments (1): https://zapier.com/engine/hydrate/11523678/.eJxNkcmSmkAAht-lz5oCmtWbinYEkdVBJ5WiWmhpZIdG0Kl595hJUpXrv32H_wPEdcVIxSL2aAhYgCWYgazqGa5iEmUJWEBBUjkZijMQDz2ry6En3ZfB85IAZUWdARzH9fCa-KfyIuRm4JqRIokqXP6exYzhmJYvUP8C5CPu0h4sPkBJ-h6nf0iAVzEvX6EqyheIeeX6Sv7fW_z4AF-55QHdEkO7H46sr5_Z6doN6SjpmzFXYGeFJXV2vTSnc3zVM6kTnB2-2OzOYdV_ewTKM0vh2JYn2WoI1AKV7CIcrAdpv0zypRbc7aQXsXSj_X5L_CbFls_vd6Rar92wMA2fOcwrpJUhH09mqkUlfwjzcIqM1iKI-iyan87UMJFu3z2MIUJuHjtT4elj0NbCO8HPxBU91-W3hmKZAZ7M3f7s1iIyirIyqExybljx13WcJIFkGg6EqxV3oVMNK6cpH2kSLsWxcg9tSy61lwXi2BUKfdNQuqFdmtqer2Xf9_YNoUw5Pjn1jm5yLYT-XHp4svc-dU1LyungHJxMv8S25Y70rPN1o8Yxfm-qrrUT7nneiqwUtNzfKK6ryVYxJMqdiy_jqJkU7VU0jbV_W2nDVg-RTLlk672--nv1zkKRwPHCt1uTgs-fn5-_AJHcyiY:1qXzKI:lmK2wzXn77JAqASlHBHB7l_EbX4/

**Comment by FALBZB** [comment]
@martinheppner  : I added the translation line to the table, please translate and produce new JSONS

**Comment by martinheppner** [comment]
The line was already there. The key is "umstiege". Your JSON files are containing this already.

**Comment by FALBZB** [comment]
yes, thanks I found it .

**Comment by FALBZB** [comment]
actually we have another one in details , i used that so translation is now done. The overlapping (on desktop even!) is a design issue, we had this before, we either shorten the text which is the translation of 'details.umstiege' or we make the container wider . here is a screenshot:



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/d2f89d4a-dae4-44d2-ad72-ee24d3bad2c0)

**Comment by FALBZB** [comment]
The Upwork guy minimized the size of the "Umst." so that is one solution, the other is what is in Figma; the  "Umst." is on another line

**Comment by martinheppner** [comment]
I created anther solution: I introduced a new line "beste_anreise_kurz" in
the translation file and checked in the JSONs

Am Di., 22. Aug. 2023 um 17:31 Uhr schrieb FALSALBzB <
***@***.***>:

**Comment by FALBZB** [comment]
done, we could the same for the share button, seems has a redundant text in many languages
