### ISSUE TITLE
Ankogel über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#105]
Von: Veronika Schöll 
Das passt wahrscheinlich nicht ins Testing Thema - aber Zuugle gibt an,
dass die Tour auf den Ankogel eine mittelschwere Wanderung ist. Angesichts
des tödlichen Unfalls am  letzten  Samstag (haben den Abtransport der
Leiche miterlebt.) würde ich das auf schwer ändern.
https://www.zuugle.at/suche?city=villach&sort=relevanz&search=ankogel&datum=2023-08-27
-- 

*Verein Bahn zum Berg*

*Zuuglest du schon, oder fährst du noch?*

ZVR: 1112324997

w: www.bahn-zum-berg.at / www.bahn-zum-berg.de

m: veronika.schoell@bahn-zum-berg.at

t: +436645345626

Attachments (0):

**Comment by martinheppner** [comment]
@veronikaschoell Die Schwierigkeitsbewertung erfolgt vom Autor oder der Autorin. Wenn du möchtest, dass die das ändern, dann musst du denen schreiben. Wir können das nicht automatisiert durchführen - wie sollte das gehen? Und bei 17.000 Touren (und mehr werden dazu kommen), werden wir das nicht händisch machen. Schließe das Ticket als won't fix.

**Comment by veronikaschoell** [comment]
Verstehe.
