### ISSUE TITLE
Loop without city

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#106]
- I am a new visitor. I have no cookie set. No city selected.
- I click on startpage on go! without selecting  anything
- I click on one tile to see the detail page
- The detail page builds up very briefly and redirects me immidiately back to the startpage

I would have expected, to be asked for the Heimatbahnhof somewhere.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/a303f6b2-f5bd-4a1f-8642-6fe077733169)

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/5708eb02-acc0-42a4-91f6-778d2fbb2a40)

**Comment by FALBZB** [comment]
done  , 


![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/ecd5b6cc-ca3a-4e6b-9ddf-8f0934e69e25)
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/0c154a11-08a5-4992-8fe9-28913ecd8c8f)
