### ISSUE TITLE
Einstieg mit Berggruppe aus Android über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#113]
Von: Gerold Petritsch 
Überlappend Texte:

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/aee41ef2-eba0-4fb4-a1e8-e4fa4e30e09b)

**Comment by FALBZB** [comment]
done in new design received from external
