### ISSUE TITLE
"Zurück" & "Filter" not translated

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#115]
Von: Gerold Petritsch (BzB) 
1. das Symbol erscheint mir nicht intuitiv selbsterklärend, Hilfetext 
beim darüber streichen?

2. der Filter ist in der Desktop Version wohl (noch) nicht anwendbar
Google Chrome: keine Schiebeleiste auszunehmen

Firefox: verschiebbar, aber kein Menu "Filter anwenden"

3. "Zurück" und "Filter" auf dt., z.B.

LG,
Gerold

-- 
Gerold Petritsch

**Comment by martinheppner** [comment]
"Zurück" & "Filter" not translated

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/6f03d347-8845-426a-b148-b3a0a80cd457)

**Comment by martinheppner** [comment]
"Zurück" is done.
Check if "Filter" is not translated (still open)

**Comment by FALBZB** [comment]
@martinheppner : not translated, please check if it is translatable to these 4 languages or if you need to translate it and create a new line in the google sheets / json files

**Comment by FALBZB** [comment]
done
