### ISSUE TITLE
Re: Filter - Richtigstellung über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#116]
Von: Gerold Petritsch (BzB) 
ad 1: mein Stiefsohn überzeugte mich, dass das Symbol schon häufig 
verwendet wird. Ist wahrscheinlich eine Generationenfrage.

ad 2: von Firefox und Chrome ist der "Anwenden" Button mit Trick (rechts 
unten PgDn) zu erreichen, von Chrome aus gelingt es mir immer noch 
nicht, zu den unten gelegenen Filtern zu kommen:

Android: manchmal komme ich hin, manchmal nicht - habe noch nicht 
herausgefunden warum.

Am 25.08.2023 um 17:44 schrieb Gerold Petritsch (BzB):
> This is a multi-part message in MIME format.
> --------------nSWpNO3SsiiASDAf0baIEFJy
> Content-Type: text/plain; charset=UTF-8; format=flowed
> Content-Transfer-Encoding: 8bit
>
> 1. das Symbol erscheint mir nicht intuitiv selbsterklärend, Hilfetext
> beim darüber streichen?
>
> 2. der Filter ist in der Desktop Version wohl (noch) nicht anwendbar
> Google Chrome: keine Schiebeleiste auszunehmen
>
> Firefox: verschiebbar, aber kein Menu "Filter anwenden"
>
> 3. "Zurück" und "Filter" auf dt., z.B.
>
>
> LG,
> Gerold
>
-- 
Gerold Petritsch

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/b249cb18-5764-4361-9a1d-25184855f41c)

**Comment by FALBZB** [comment]
need some clarification on his comments

**Comment by martinheppner** [comment]
I understand it that way, that on Gerolds mobile, the fixed bottom line was sometimes there, sometimes not. Then he could not use it.

**Comment by FALBZB** [comment]
What is the " fixed bottom line ", you mean the footer ?

**Comment by martinheppner** [comment]
Bei Gerold nachfragen, wo das Problem genau liegt. Kann nicht reproduziert werden.
