### ISSUE TITLE
Übersetzung Öffi-Verbindungen über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#117]
Von: Gerold Petritsch (BzB) 
zum Teil noch deutsch: Umst., "Ankunft bei Tourende"

-- 
Gerold Petritsch

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/0c919c1a-b016-42b5-992f-f570d68c31aa)

**Comment by martinheppner** [comment]
What are our options here? Let's talk about them prior starting coding.

**Comment by FALBZB** [comment]
We talked about this before, you then said that this will be done at a later. stage, we can find a method, but it will take time, will not make it this week
