### ISSUE TITLE
Übersetzung Impressum etc. über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#118]
Von: Gerold Petritsch (BzB) 
funktioniert nur aus dem Fußleisten Menu , nicht aus dem UAT-Menu oben links

-- 

Attachments (0):

**Comment by FALBZB** [comment]
No idea what this is about, how can i translate from the footer where the impressum is there, the local version i am looking at works fine

**Comment by martinheppner** [comment]
This is not about translation, the links in the new menu on top are not working in the same way, as in the footer.
