### ISSUE TITLE
change translation of "rückreise_moeglichkeiten"

### ISSUE THREAD

**Issue by FALBZB** [bahnzumberg/zuugle-suchseite#119]
The purpose is to make the number of additional return connections a dynamic one. to simplify the process we selected a version of the text in each language to be such that one can insert a number in front of the translated text and the result of this augmentation would still make sense in all 5 languages.
@martinheppner : please check the  preliminary translations  and push the new exported json files to repo.

**Comment by martinheppner** [comment]
Where do I find the preliminary translations? They are not in the Zuugle-Translations File (I would expect them at the last line, to know in which order they have been inserted)

**Comment by FALBZB** [comment]
@martinheppner : i did not create new ones, just modified the existing ones, in the excel Line 168

**Comment by martinheppner** [comment]
Update JSON done
