### ISSUE TITLE
Fwd: [bahnzumberg/zuugle-suchseite] 8d8e8b: add pdf and gpx buttons visible only when menu lan... über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#120]
Von: Martin Heppner 
The pdf button should only be visible, when menu language is "de". This is
correct.

But the gpx download has nothing to do with the menu language. It
depends only on the new column "allow_gpx_download".
Please adapt accordingly. Thank you!

---------- Forwarded message ---------
Von: FALSAL <noreply@github.com>
Date: Fr., 25. Aug. 2023 um 18:06 Uhr
Subject: [bahnzumberg/zuugle-suchseite] 8d8e8b: add pdf and gpx buttons
visible only when menu lan...
To: <martin.heppner@bahn-zum-berg.at>

  Branch: refs/heads/dev-drop-slovenia
  Home:   https://github.com/bahnzumberg/zuugle-suchseite
  Commit: 8d8e8b18777da19699f754b2da16b165fedbf9fc

https://github.com/bahnzumberg/zuugle-suchseite/commit/8d8e8b18777da19699f754b2da16b165fedbf9fc
  Author: FALSAL <coconto.info@gmail.com>
  Date:   2023-08-25 (Fri, 25 Aug 2023)

  Changed paths:
    M src/views/Main/DetailReworked.js

  Log Message:
  -----------
  add pdf and gpx buttons visible only when menu language is de

Attachments (0):

**Comment by FALBZB** [comment]
please check now

**Comment by martinheppner** [comment]
I am looking at a tour from provider "bahnzumberg" on the detail page. 
I have selected Slvovenian language. 
I would expect to find NO pdf button, because of the slovenian language
I would expect a gpx button, because this provider has no flag "no_gpx_download" set (https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=33410200)

![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/741e86fc-42c8-43b9-8bbe-a1ca0c42c5df)

**Comment by FALBZB** [comment]
OK, done
2 screenshots for this example : http://localhost:3000/tour?id=9025&city=salzburg&sort=relevanz 
one in german, the other in english

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/afc95d41-7be4-44cf-b59b-a255514d0571)



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/d4229fbd-b3e5-461c-be3d-b8a018ae1525)

**Comment by martinheppner** [comment]
done
