### ISSUE TITLE
Use Github Actions to automatically deploy to UAT

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#121]
We could define a branch UAT, which we could use for automatically deployment. Whenever code is merged to this branch, it should be build and deployed to the UAT machine.

HowTo: https://eliaslog.pw/how-to-github-actions/

**Comment by martinheppner** [comment]
Suchseite is set up.
API yet to do.

**Comment by tobHai** [comment]
Hi, d.h dein initiales Problem mit den Github Actions ist behoben? :)

**Comment by martinheppner** [comment]
API automatic deploy to UAT working now, as well.
