### ISSUE TITLE
Multiday Tour - days not duration

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#122]
Having a multi day tour at hand, we should show the days in the itinerary, not the hours.

![Image](https://user-images.githubusercontent.com/105971399/263440883-f9574afe-bc70-4dff-ae09-c67243e793cc.png)

**Comment by FALBZB** [comment]
Thats right, this is on my plate already. Will be moved to in progress

**Comment by FALBZB** [comment]
@martinheppner : please translate the last line inside Google sheets with key = "tage"

**Comment by martinheppner** [comment]
Translation JSONs pushed.

**Comment by FALBZB** [comment]
@martinheppner : its done now
