### ISSUE TITLE
0 connection - do not show text

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#123]
If there are no more connections home - do not show the text.

![Image](https://user-images.githubusercontent.com/105971399/263440944-c18881ab-f01b-44c4-999d-0bbaeae90572.png)

**Comment by FALBZB** [comment]
@martinheppner  : Give me a link or a tour id  i can test,

**Comment by FALBZB** [comment]
@martinheppner : done ! try it yourself please

**Comment by martinheppner** [comment]
Tested, working
