### ISSUE TITLE
Share button has no function

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#126]
At the moment it seem, that the share button on the detail page has no function (e.g. on https://www2.zuugle.at/tour?id=9943&city=klagenfurt&sort=relevanz). Clicking on it does not show the additional options, I would have expected underneath.

**Comment by FALBZB** [comment]
My local set up works : here is a screen shot:

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/252b9d1b-ab25-4fac-8445-057975a8a44a)

**Comment by FALBZB** [comment]
I changed the function (or event handler), try it now please

**Comment by martinheppner** [comment]
I build it locally and transferred it to UAT. Tested it with https://www2.zuugle.at/tour?id=10446&city=klagenfurt&sort=relevanz
Share button does not work.

The table disposible is empty.
