### ISSUE TITLE
Linking button has no function

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#127]
The button, which should link to the original tour - and open it in a new tab - has no function.

![Image](https://user-images.githubusercontent.com/105971399/263442399-927d56b7-9472-4afa-8de5-5122adb76f43.png)

**Comment by FALBZB** [comment]
Here is my screen now using : http://localhost:3000/tour?id=9025&city=salzburg&sort=relevanz

I get the link to : https://www.bahn-zum-berg.at/berchtesgadener-alpen/von-felstuermen-und-burgruinen/

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/3c4b7a7e-0746-4b32-945a-632ccb3cf276)
