### ISSUE TITLE
translation : "Click to select your home station."

### ISSUE THREAD

**Issue by FALBZB** [bahnzumberg/zuugle-suchseite#128]
This is needed for the overlay text that pops up when user arrives at the detail page without a selected city.

**Comment by FALBZB** [comment]
I managed to enter the German and English translations in the last line of the excel sheet, L191

**Comment by FALBZB** [comment]
@martinheppner  :There is also a new text line that belongs to this same button, i added it to the excel sheet also:
"um_reise_berechnen_zu_koenen"

**Comment by martinheppner** [comment]
Update JSON done
