### ISSUE TITLE
total_tours_city as number on startpage

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#129]
In the API the value for "total_tours_city" is already prepared, to show the number of hikes reachable from the selected city. If no city is selected, the value for "total_tours_city" is 0. In this case "total_tours" should be used.

![Image](https://user-images.githubusercontent.com/105971399/263463177-5899fd49-0d73-4723-b794-ceaae82c7369.png)

**Comment by FALBZB** [comment]
Ok, looks like there must be a call made to the dbase to get the figure , or can you remember that we had it already in the front end ? suchseite?

**Comment by martinheppner** [comment]
A good starting point is tours.js file in API. The SQL is already adapted and returns with every call not only the total_tours, but also the tours_city. This new value shows the amount of available tours for this city. The new return line is prepared. Has to be enabled and from there used, if a city is set.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/e55b729e-4c10-479e-863e-30cf886eb077)

**Comment by FALBZB** [comment]
done, so every time the city changes through the select city inside the search bar it updates the value of the number of tours received from the backend, i.e value of tours_city
