### ISSUE TITLE
New UIX

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#13]
**Version 3: Mobile & Desktop:** https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0

**Comment by martinheppner** [comment]
The image is only set with the provider "bahnzumberg". All others are empty and the space should be blank. In the screenshot it is marked red.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/4bf4cfd8-4592-4fee-a6c6-88acf80bfede)

**Comment by martinheppner** [comment]
Header and Footer should be useable on all pages.

**Comment by martinheppner** [comment]
The blue button holds a link the the description of the hike on the source platform. Clicking on it, should open it up in a new tab.

**Comment by Cleatuer** [comment]
> The calendar section is always showing 7 days. Today is always the first entry on the left. If there is no parameter "datum" set, the current date (today) should be shown. If there is a valid parameter - e.g. &datum=2023-05-15 - then this day is selected.

@martinheppner  Must the parameter in the detail URL be called "datum" or is "date" also ok?

**Comment by martinheppner** [comment]
Has to be called "datum", because no parameter must be removed. Otherwise the links of some partners will not work anymore.

**Comment by martinheppner** [comment]
Welchen Umbau wir auch immer vornehmen, die jetzt gültigen Links müssen weiterhin funktionieren, oder mittels Umleitungen berücksichtigt werden.

Beispiele:
https://www.zuugle.at/suche?p=alpenvereinaktiv&sort=relevanz&map=true
https://www.zuugle.at/?city=wien&sort=relevanz
https://www.zuugle.at/suche?city=wien&sort=relevanz
https://www.zuugle.at/suche?city=wien&sort=relevanz&map=true
https://www.zuugle.at/bischofshofen
