### ISSUE TITLE
Result amount 2x on mobile über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#132]
Von: Martin Heppner 

Attachments (1): https://zapier.com/engine/hydrate/11523678/.eJxNkdmOokAUht-lru0JO4V3igtIqwgiymRCaCgWWQqqCm3o9Ls30zOTzO35l-8k_weIccNQw0I2tAjMwQLMQNFQFjUxCosEzEVBhpwiSjMQ95ThuqeIfAs8LwuiosIZiOIY91PFvysvidwMpAWqkrCJ6t-1EWNRnNcTiE6A8hmRjIL5B6gRpVH2hwR4GImCwskS0rgEqtzk_D83__kBvn2Lw_ae7GCSZjapNiU-LgbnvC3vsevn0Ao5W7HhW1hur50Tvz8fZh4k3Uvf-e-iuaIp2yeDOqXlQh1d8tSHytsy_0awvtPfON_13mxNK84qhXdqSoFuDGevv8D9mp5OUqx4dqQaK-2orwzVV42L4rFHftZfU3-jxCph1XALbDdo_aXGP0W6rNnoZHvbPYt6v-qOx-X1pNwdSaiCYYXTJrlcr6RapFIHA3zKUbuRbyS31XY3PLJisTJ2FtUJz2CyCx55M8ak2osqFwqjuTbFzaHnuRSNG4TLl_EiOVstY7fRchwqv0dYkqNWtNLtyc4Sj_nFvsRhwSA2O93qjvKQGM8CyUmL-UO2DqWWWF653Ni4PXiVMX3gwkibcrxpFet1l7266atxkq-mVt319pqgEt760XbrR29PW_2d2o0JQg3NMQsFThA5KCghr3KCIIV6TnCNftzbDHz--vz8AlPs0zI:1qZv4W:MemQzbp6b45sfsLWoiIfmyl5CWE/

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/e1e9a4df-66ea-4b27-8c11-c7905ef8a6c8)

**Comment by FALBZB** [comment]
done
