### ISSUE TITLE
Provider URL link not showing for some detail pages

### ISSUE THREAD

**Issue by FALBZB** [bahnzumberg/zuugle-suchseite#139]
I have checked the postgres table and there were data missing at the column url see screenshot

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/3e9135c8-7830-4b10-9c0a-e616097e8b98)

This is the effect in the detail page:

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/81a6ea6c-4441-4373-8a00-b7ded5b92a6c)

**Comment by martinheppner** [comment]
Updated corresponding View on MySQL side. This was the source for this problem.
