### ISSUE TITLE
Ranges auf Startseite und Filter auf Gebirgsgruppen nicht deckungsgleich über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#141]
Von: Gerold Petritsch (BzB) 
Hallo nochmals,

bei Auswahl der Ankogelgruppe auf der Startseite erhalte ich 4 
Ergebnisse 
(https://www2.zuugle.at/suche?sort=relevanz&range=Ankogelgruppe&city=amstetten)

über den Filter nur 1:
https://www2.zuugle.at/suche?city=amstetten&sort=relevanz&filter=%7B%22coordinatesSouthWest%22%3A%5B%5D%2C%22coordinatesNorthEast%22%3A%5B%5D%2C%22singleDayTour%22%3Atrue%2C%22multipleDayTour%22%3Atrue%2C%22summerSeason%22%3Atrue%2C%22winterSeason%22%3Atrue%2C%22children%22%3Afalse%2C%22traverse%22%3Afalse%2C%22difficulty%22%3A10%2C%22minAscent%22%3A0%2C%22maxAscent%22%3A3000%2C%22minDescent%22%3A0%2C%22maxDescent%22%3A3000%2C%22minTransportDuration%22%3A0.2%2C%22maxTransportDuration%22%3A5.15%2C%22minDistance%22%3A0%2C%22maxDistance%22%3A80%2C%22ranges%22%3A%5B%22Ankogelgruppe%22%5D%2C%22types%22%3A%5B%22Bike+%26+Hike%22%2C%22Klettern%22%2C%22Klettersteig%22%2C%22Langlaufen%22%2C%22Schneeschuh%22%2C%22Skitour%22%2C%22Wandern%22%5D%2C%22languages%22%3A%5B%22XX%22%2C%22de%22%5D%7D

Warum der Unterschied?
*In beiden Fällen kann man leider nicht mehr auf eine andere Region 
umsteigen.**
*

LG, Gerold*
*

-- 
Gerold Petritsch
*Verein Bahn zum Berg*
ZVR: 1112324997

Bahn-zum-Berg.at <https://bahn-zum-berg.at>
www.zuugle.at <https://www.zuugle.at>
t: +43(0)650 2073 866
Attachments (0):

**Comment by diditrummer** [comment]
is obsolete when redesigning start page
