### ISSUE TITLE
replace color blue with green color in PDF

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#144]
The new maps shows Zustieg und Rückstieg as a green line. Begore it was a blue line. In the PDF it is still blue, but should be adapted to match the new version.

**Comment by Falsal** [comment]
@martinheppner : can you make a screenshot of "Zustieg und Rückstieg as a green line" ?

**Comment by martinheppner** [comment]
I can not even create a PDF (on my mobile)

![Screenshot_20231114_045452_Chrome.jpg](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/26ccd742-e3a1-426e-9a6e-dd71c7efdb0d)

**Comment by Falsal** [comment]
completed it on dev, must be tested

**Comment by Falsal** [comment]
Unable to see the changes in the code, there are other issues that must be checked.

**Comment by Falsal** [comment]
This pdf feature will be removed temporarily. Take a look at #377
