### ISSUE TITLE
Range filter not working correctly

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#148]
The URL https://www2.zuugle.si/glocknergruppe?city=ljubljana&sort=relevanz&range=Glocknergruppe should filter only on hikes, situated in "Glocknergruppe". But it shows many others.

![Image](https://user-images.githubusercontent.com/105971399/264383412-f5cbb3a6-fbda-4792-b80d-81597796c5f0.png)

**Comment by FALBZB** [comment]
I suppose it is the same issue that is solved in #204
