### ISSUE TITLE
Get share button working

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#159]
Share button is not working at the moment, so we deactivated it from Drop Slovenia.

**Comment by FALBZB** [comment]
But working locally on MacOS, that is an important distinction.

**Comment by Falsal** [comment]
The following is a screenshot of the console logs in my local machine, the one after is the UAT same log:

Localhost:

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/af365a44-9487-489c-8ecb-84a3b2421d61)


UAT:



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/329b9f4c-4c32-4248-bb9e-79f246200aa3)



There seems to be no shareLink generated on the UAT, can we check the table (disposible) on UAT to see if it does create a shreLink and stores it in the table? 

here is my "disposible" table screenshot:


![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/9667e0d7-c27b-45b8-975b-236309167ba1)

**Comment by martinheppner** [comment]
Empty resultset on UAT received after executing "SELECT * FROM disposible".

Where would I search for the error messages?

**Comment by martinheppner** [comment]
The credentials are for the database. There you will find no error messages. Access to UAT environment over SSH is available for you since a long time and you could connect any time you want.

**Comment by FALBZB** [comment]
I have been getting some online Nginx knowledge, now i have the keys which
you have sent me in August, (see next email ) , so now:
1) please resend me the link to the server where I can access UAT server
with these keys
2) Also what tool do you use ? I would also like to use that same one.

Br, Faris

**Comment by FALBZB** [comment]
Ok, please show me in the meeting how you access the server using putty and
any other tool to view the file "nginx.conf".

According to my research:
on macOS, i would not need putty (terminal emulator) to access the remote
server, I would need it only to transform format from .ppk to .pem,
Now to access I would need to enter :

*ssh -i /path/to/your_private_key ***@***.****So i have the path to
my private key, and i have the hostname, but i need the *username*

**Comment by FALBZB** [comment]
Good morning Martin,
I have pushed the QR code to branch "initial" , what we need now is to add
production values to the config file, also code inside a db.js file should
be commented out .
see you at 09:30

**Comment by Falsal** [comment]
status 08.01.2024:
Share button showing now but the link provided is not correct. Need to investigate the reasons and fix it either from the api side or from suchseite .

**Comment by Falsal** [comment]
The link is correct but will change the next day and may not be usable then.
Here is an example here : https://www2.zuugle.at/tour?id=159027&city=baden&datum=2024-01-12

one possible solution I see:

- as share links are created : replace the id in the params with the tour-title  (we can limit the number of characters of title string)
- then (if date in params is old ,  update the date to be the current date in the url , otherwise keep the selected date if it is in the future)

lets discuss it in our call

**Comment by martinheppner** [comment]
I do not understand your example link. The id of the tour is of course invalid next day, as we are loading the ids every day new.

This is why we introduced the concept of the disposible links https://www.zuugle.at/tour?share=58420b75-e17e-45cf-81a2-75a193d8eaaf, which can be read in the background from the table and translated to provider and hashed_url to find the one result again. 

![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/9bf3358d-351b-4f57-b52d-aef35364e2f1)

The one result has a new id and with this new id the page has to be called. This seems not to work at the moment.

**Comment by Falsal** [comment]
just a thought in my head, that i wanted to unload :-)

anyway, i tested it on UAT and it seems it works now. Unless I am missing something. But i generated the link with the share button and used it in a another tab , this gave 
just to double check i queried "diposible" table if the share "link" column had this new entry , that also was done

**Comment by Falsal** [comment]
http://localhost:3000/tour?share=f9957a8d-93a3-4d78-bec4-602fe5ede043
The shared link above was tried at 23:50 on the 16th Jan 24
Note the first date in calendar is the 16th:


![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/d912eecf-bf4c-4934-a61a-f77322337d4d)



The next day Jan 17th I clicked on the same link above and got this:   
showing the 17th  as the first day in calendar


![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/75b2b9fd-66c8-4b39-9914-ed74950be72a)

**Comment by martinheppner** [comment]
I would like to test it on UAT: Today 17.01.2024 with city=amstetten generated the link https://www2.zuugle.at/tour?share=4bece96e-680a-4118-9b24-4fabc6122b1c for tour "In Schneeschuhen auf den Hochwechsel"

**Comment by martinheppner** [comment]
Reopening this issue, as the link https://www2.zuugle.at/tour?share=4bece96e-680a-4118-9b24-4fabc6122b1c is not even working on the same day on UAT, if  I open it with a private tab. :-(

**Comment by Falsal** [comment]
ok, it must be something related to localStorage 
will check it out,
