### ISSUE TITLE
#Suchergebnisse in German on Slovenian language page

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#160]
I selected language Slovenian and searched. The # results are in German ony mobile phone - see screenshot.

![Screenshot_20230903_173153_Chrome.jpg](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/474162cd-804f-4c63-9160-1bb755192d00)

**Comment by FALBZB** [comment]
done !
