### ISSUE TITLE
Zuugle.si should start with slovenian menu language

### ISSUE THREAD

**Issue by FALBZB** [bahnzumberg/zuugle-suchseite#164]

**Comment by martinheppner** [comment]
i18n is quite smart: It checks the settings of the used browser and shows the visitor the language, he has set on his computer. 

Unfortunately i18n shows Google the Slovenian page in English. In this case it should have been Slovenian. See screenshot. The question is now: Is this i18n or our doing?

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/6442315c-57c3-4bc6-8bab-e265af2f8fd2)

**Comment by martinheppner** [comment]
See Readme at https://github.com/i18next/i18next-browser-languageDetector

**Comment by martinheppner** [comment]
Google Input: https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites?hl=de

**Comment by FALBZB** [comment]
how far are you in this issue?  one tip i can give is the configuration of the file src/translation/i18n,

we probably only need to add in the options the order from where language is to be detected: 

  order: ['querystring', 'cookie', 'localStorage', 'sessionStorage', 'navigator', 'htmlTag', 'path', 'subdomain'],

**Comment by martinheppner** [comment]
As I wrote in may mail: My computer is unusable at the moment. I have to fix this. It is slowing me down and I am affecting you as well, as you have to search for the errors I put in.

Regarding this whole topic: Yes, please try the adapted order!

**Comment by FALBZB** [comment]
i18n new config for LanguageDetector the order options added. Should be tested now
