### ISSUE TITLE
Višinska razlika

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#170]
Jernej T.:

![Image](https://user-images.githubusercontent.com/105971399/266300476-620862d5-f3af-452e-9d53-604c1f579345.png)

**Comment by martinheppner** [comment]
Die leere Sportart gibt es auch in anderen Sprachen:


![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/d2a86888-600d-4877-b7ef-14f1a791d8cf)

**Comment by FALBZB** [comment]
I don't see where this is showing ? currently in PROD or in AUT, if still exists, please tell me how to reproduce. here is the current version i have:



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/c0ba1280-af78-458a-a419-1cb89b142924)



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/c446deee-edbb-4fe3-852c-6f52e6545e70)



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/0737964b-bd93-4639-b212-dca939f79f5b)

**Comment by martinheppner** [comment]
It is there, but only if there is a tour with more than 3000 HM. It works as dsesigned.
