### ISSUE TITLE
Map size for Slovenian tours needs to be adjusted

### ISSUE THREAD

**Issue by FALBZB** [bahnzumberg/zuugle-suchseite#181]
see screenshot, currently in production

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/df51d722-f2e6-4ef7-8c14-8cb0aadfe1ed)

**Comment by FALBZB** [comment]
possibly an API issue

**Comment by martinheppner** [comment]
Nothing to do with Zuugle. I know where the problem is coming from, but not how to fix it. We are powering a proxy of Opentopomap for our own services. The deepest level of the map is not working properly. I could not find a solution yet.
