### ISSUE TITLE
Add city to Header dynamically

### ISSUE THREAD

**Issue by FALBZB** [bahnzumberg/zuugle-suchseite#183]
if city is unavailable then the old text the generic one will appear, translation files must be changed and interpolation used

**Comment by martinheppner** [comment]
The City must not be the city_slug, but the city_name (which is used in the Heimatbahnhof search field.
baden -> Baden
wr-neustadt -> Wr. Neustadt

**Comment by FALBZB** [comment]
You did not mention above why you need to do that? 
if it is for the purpose of making the city name start with a capital name then we have a simpler solution (solution 2 below):

solution 1: extracting city_name 

 useEffect(() => {
    if (!!city && !!allCities) {
      const cityObj = allCities.find((e) => e.value == city); // find the city object in array "allCities"
      if (!!cityObj) {
          setCapCity(cityObj.city_name)
      }
    }
  }, [city])

solution 2: changing the same "city" name into a capitalised first letter:

 useEffect(() => {
    !!city && setCapCity(city.charAt(0).toUpperCase() + city.slice(1));
  }, [city])

**Comment by FALBZB** [comment]
@martinheppner :In any case we have now to change the translation files, I already replaced the {{city}} with a state variable {{capCity}}, please push to UAT these new files.

**Comment by FALBZB** [comment]
changed both the search city input as well as the header, it works smoothly now

**Comment by martinheppner** [comment]
Super!
