### ISSUE TITLE
PROD Domain Dialog distorted

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#186]
The logo (left) and the icon to close (right) should be in the first row. 

![Image](https://user-images.githubusercontent.com/105971399/266827309-1801c3ba-7f9f-46c0-a5a2-83baea7943bd.png)

**Comment by martinheppner** [comment]
On current UAT the logos are not to be seen

**Comment by FALBZB** [comment]
fixed the UAT , except that the width is made optimal for the PROD so in UAT, the order is fine but only the first on the list the word UAT is squeezed up a bit, this will not be visible in PROD.
