### ISSUE TITLE
Hide id in detail page

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#187]
Hide the yellow part

![Image](https://user-images.githubusercontent.com/105971399/267089355-aa05a305-bcd8-44e0-abfb-7b812003bec6.png)

**Comment by Falsal** [comment]
@martinheppner : first 2 options below to solve this issue are relatively fast in implementation:

1) useNavigate() React hook: easy to implement with minimum changes, works well within react of course, can be completed today, BUT cannot open detail page in a tab.
2) remain with window.open() which is a pure Javascript method. is also doable. BUT must use localStorage to store the id of tour when opening the new tab for detail page. Can be completed by tomorrow afternoon.
3) Redux store: I tried it but did not work for me, I am sure it would work IF i have a few more days.
4) Context API : this is a compact version of Redux as a state store for universal use inside the program. Not difficult to do, but would add an additional tool unnecessarily . Can be done by tomorrow afternoon.

I personally would go for option 1, what is your preference here?

**Comment by martinheppner** [comment]
I would choose 2.

**Comment by Falsal** [comment]
@martinheppner : Good choice ! I just completed the work, it was actually much simpler than i thought, sorry for the bad estimate .

**Comment by martinheppner** [comment]
Cool.
