### ISSUE TITLE
PDF translation

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#20]
PDF content should be in menu_lang as the website is.

**Comment by Falsal** [comment]
[Create 5 template files in API](https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=29587738 )

**Comment by Falsal** [comment]
Basic functionality is now set, what is needed is :

- pulling connection data for translation 
- creating the actual translation JSON

So i consider this issue 60-70% completed.

**Comment by martinheppner** [comment]
https://github.com/orgs/bahnzumberg/projects/2/views/12?pane=issue&itemId=30353679

**Comment by martinheppner** [comment]
Within this ticket the use of the standard JSOn language files are included. "Ugly JSON" is acceptable. Beauty is overrated.

**Comment by martinheppner** [comment]
PDF feature has been deactived, so this issue will not be implemented.
