### ISSUE TITLE
Closing pointy bracket wrong position?

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#202]
This does not look ok to me. I think the closing in line 48 should be in line 42.  Can you please check?

![Image](https://user-images.githubusercontent.com/105971399/269023717-09399a6f-a535-44ad-a12e-c159ffd5c5eb.png)

**Comment by FALBZB** [comment]
@martinheppner :
your screenshot does not show the closing angle bracket of the first div inside the Suspense , in the code it is there, otherwise **the brackets in our code at the moment are complete**, if they were not, the VS code would give me an error in the "Problems" section in its terminal.
