### ISSUE TITLE
Filter count changes suddenly

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#208]
I open up www.zuugle.at

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/28a69f0c-367d-40ee-b516-27128a5cf7d2)

I select Vienna and click on Go

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/4c41c9dd-e627-43e0-a265-a1555c7f259d)

I set the filter to >800HM and <1,5h 

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/632c11ba-7c12-4721-abf4-2405c1a74e66)

Result: 82 hikes

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/0c67029c-0977-4b83-bab9-120552a16aca)

I scroll and suddenly the count changes to 191

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/a23dae42-80ae-4c72-83ec-09407aa87b47)

Further scrolling does not change the result anymore.

**Comment by Falsal** [comment]
@martinheppner : completed , but need to cleanup (test code, clgs and comments) before I can update UAT and PROD. This will be done in the evening

**Comment by martinheppner** [comment]
Very cool! Thank you!
