### ISSUE TITLE
Improve Mobile Search / Heimatbahnhof Dialog

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#210]
Von: Stefan Hochhold 
. Vorschläge wäre hier sinnvoll (zB. meistaufgerufene/gesuchte/geklickte Regionen/Wanderdestinationen)
. Statt Pfeil rechts sollte hier ‚GO‘-Symbol stehen, wenn – wie in meinem Fall – der Heimatbahnhof bereits ausgewählt war. Nur bei noch nicht ausgewähltem Heimatbahnhof steht der Pfeil und suggeriert weiteres Interaktionsfeld

Wordings:
. Eigentlich hatten wir statt ’Suche’ den Begriff ‚Öffi-Touren im Alpenraum‘, weil man dann einfach ohne Sucheingabe Ergebnisse erhält
. Falls dies ein Problem darstellt, weil User womöglich nicht wissen, dass sie diesen Begriff überschreiben können/sollen: Ev. in Grau darstellen oder Wording ändern zB. in ‚Wandertour, Ziel, Region, etc‘ 

. (!) Wichtig: Im Prototype-Design haben wir uns ja festgelegt auf 'ab {Heimatbahnhof}‘. Das ‚ab‘ ist hier wichtig, weil es beschreibt, was mit dem Item gemeint ist. Wenn nur die Stadt dasteht irritiert das, weil es ja auch ein Suchbegriff sein könnte. Bitte unbedingt ändern. Falls die Übersetzungen des Wortes ‚ab' fehlen: Vorläufig zumindest ‚Heimatbahnhof: {…}‘ voranstellen (oder in Klammer schreiben).

. Bei der Mobilen Version ist jetzt die Suche und die Heimatbahnhof-Auswahl getrennt dargestellt. Was ich als sehr problematisch sehe. Weil man mit am Smartphone nicht so zielgenau tippen kann. Das Design macht nur Sinn und funktioniert dann, wenn Suchfenster und Heimatbahnhof-Auswahl in einem Fenster dargestellt und eingestellt werden. 
Oder gibt es aber einen anderen Grund, warum das so gemacht wurde, wie’s derzeit ist.

Attachments (4): https://zapier.com/engine/hydrate/11523678/.eJyV0Uevo2gWBuC_UvL6ckUOtSOZYDBgk1stRAaT4SO5VP997lTPSN1Sb2p3dNK7eH5c0qEHeQ8icI755fuFvXxc6n4BcZ_mUZ1dvmMoQcMkhn9c0nUBQ7cu-fxrgCAEipEU_XGJ03RYv178v4vgGPxxKeq8zaI-7v77NgYgTqvuK2j5Cmj2eC6Xy_cfly5flrj8K-mC0HFeUHme0QiNMBj-tfn3u-9__Lj82mPv0itTo3NEBAcRdasRZsfM8BlSFdj2GnGXijuirBqaD27Ve689H9VQvtKe4UJ3xKXOQItGIatyuYmodaQaBAxNd7M4yOPzfTreyOlCLQ27s03R4RYI7GY2722H6Gnhkvg6igJQ63JkedkrKDgYeLveXnE4BkbLN2dO55X2WGxvKK956Tcb8NSjJ8Ulz45ADkmI8pQE95T2BcwZQWt82FPDVABTAcErkaVgXTHEhZaiM07VYWpljQGd7NeVrlw41a8NAUEHlAWdz0Q9K_NBshpTFoCj965GpsvURp-8254EF2o9Qjq9cnQNTmLXBXRB84R3fz8cWZS1-5BGvnyjyN3pRaKnONuh85tqS4NyJysIEHupaCa1w_keozwbG6t4C8o3UWzTO0B6rMTs0chSz-lJ88vqf9Rc3WZLWtVzVwxg-IbCKAYhMASj39buGwJ_wvAnQnyOfXn5-fEPUIYnmoBxBHHiAw0LxFG_Cv5rcRJ-KjbiPOws06zO7PwCXzfy4BfPoNNOojVljue5maIA3rcHFnn1ehza3nQklN_Ghi-hgp4quW0GwcA8hRJRKWEJlPaXiTi6VpdE1lyVB_Rqm3Cyk36CjLbQmPDKOnYnNzYbDHd_bGS112vpnVRzgLBcMz-vQQRW0iCzQGHwBLui58yCQ18ZtUep7Mnabx-s2_6C9Qqm0q6Pqy66XTOI7kvXysxxMuIu6QzVt8JqT3pzXgfoVePs235HXPXi3-Y5ho5_LVBoXlZ8nvbGABZiWxFUP0VL7_YO6Zp9ssFElbMGL7JstK6UyPT2MN4IWiAzmsc0c55P0mfI6X6nq66HCLC9Nx9uhJHmOUhyXTyAwl44bEr1squaJM6LS5btN0DxTxT9N1Do7j8OmHQcXvJQP7GA0O6B0-2Pw89fBnjY9bvnnVk4Etx5XOkjqK82bym3QVW_yriFilt8sElU7-QRT4JXYNaoTSTjvJ-FIBWtdHIr7cJDyBvxEqVDu_qWXidOKbJU521jpmER2u4ZMXtcKpBBIDfa-DBYkKa3QHZWEDFaKwR6yrIP_4VaZauTWW68bPe5sjFC2FbdBxiyaBbrn9aZm5DaoWTRxo3xUKp0cMKB7m0eDhzxsDy4mCNmoSCLSAQptWziBtZVqT2E1Gl6ZtJJw0jgg-PuiRz3qq7Zm8wsOLRvHgIexsjUu1HqRX3HQdyVTJS8rFfddwWXHsMzRJfCdpNM3eNB8ZUj2p_6W1yDCO4eiFSmDGbzFXlzjB1iFrtS7mxjYi5thU9DKuT6ZhdE8xugzCf8r6C0nDuZZsPdnZQqJOmf0Lqmwhmcz9NzBTEkNsKsaHIVUhplw8MXz2MWxjoW5mHeo0m_T4VQC_mtoMBNusbK_Qm4qswYYnXxmcWixfUS6vbMG3mcWB-xhj5pADUNVhimyr1LzV5mZWayCzHhUM48555c8NM6TEA3-33VCetJNDtRUTKBzn3DyMZUH7gd3HDwIleFN-G3wcvh1falJmd87Oobfakb05dag6g8tqz0zVsdNdF7WhLmhdp0o-vI1oXsYJOlfnYwuBbltnof8oYYus3xDhCtPSf0blEgy1WRlVnUxEOVAAtkG3HIgyFz_A0eo9xhnPQShpHwj2ce6XcKwcN9celSPIJUWwd884BWu_3SB4lA2pzKSGkn-iR2ag_bA3rrmzwhZvk2-d5uIs_3b4DSnwT8F-ifP3_-B1DSoLo:1qnETI:zXZ_aNB1sIxj1EED8CVM3tlke3Y/

**Comment by diditrummer** [comment]
additional window:

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/87718607/a63ddcd9-3b95-4f6d-9734-ef161a2ef0b8)

**Comment by martinheppner** [comment]
The search icon should only be used with the search. In this dialog the train icon should be used

![Image](https://github.com/user-attachments/assets/11caae5e-0cf1-435e-8cb2-7e7b46552905)
