### ISSUE TITLE
Umstiege im Fahrplan überdecken Text in Start-Karte über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#212]
Von: Stefan Hochhold 
. https://www.zuugle.at/tour?id=543234&city=linz
. s. Screenshot anbei.

Attachments (1): https://zapier.com/engine/hydrate/11523678/.eJxNkclyokAAhl8lxVlSTTerNyIGFNyiBsjUFNU0SxAakG5EtPLu42Rmqub6b9_hvwukqXla84iPbSpMBVOYCEXNOK5JGhWJMEVQ0YGK5IlAesYb2rO0-zYkSYFI1fSJgAlp-sfEP1WSEZgIWZFWSVRj-nsWc47JJ32A2ANQDrjLmTC9CzRlDOd_SIKk4zQzdJgBLSaYJI_k_73pj7vwnTPX9ilZik4R29FqGE9yWa2Cs1iiJWipWIR7czOzXHkd74_rgLJka-_dncH9ZZ1eeOndNgU-jaMYLIwukHB8vOCx9BN9DlctVemnndiaGflGiMi7_1G-5WeLXpxD15iLtd3q5qYlxtClyeHifOTHrJ4DPo9vlQNEZfV6mxk7tNiIYNtC7eqFK0-nW7nvx667wRHIOy23wqutJ9CXVAp5tYJLrU_ZC3JP5xfADh9DpxiqV0iay3XDc8d3HLoH3pMgCmayQxdVmqlDsd-Yu9ijUBm0LQPowKzC1w7BJkM6z0OdS6-OBVjsHUmIu7cTka3ZsEBGcVlclbRxyu2czwe_VUlvXVCSaYnoQZNte8U3ousyNbzEAq0-o7sI5rWH4tcxJDt7BdTMXzcFcmNZY-cK1PEeH-VjrDy--nv1S1EljHwWHc0a3jxBAJEoARHAp54-SeBZkZ6h_NzWufD18-vrF9UZ0C4:1qnEvw:RkfFQwZXsMbL455tRYHDx4ZL4qw/

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/7b34c1ae-ce79-4512-b504-d5626e03ae07)

**Comment by martinheppner** [comment]
https://www.zuugle.at/suche?id=588477&city=linz&search=Genusstour+Botanischer+Garten+Linz+und+den+sch%C3%B6nsten+Aussichtspl%C3%A4tzen

**Comment by Falsal** [comment]
Fixed now, here what the "Genusstour Botanischer Garten Linz und den schönsten Aussichtsplätzen" looks like now:

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/d0c2c0de-b111-431d-879f-6e71cca8e0dc)

**Comment by martinheppner** [comment]
Tested it. Works. Thank you!
