### ISSUE TITLE
New translation method for getPageHeader (Helmet Meta data)

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#215]
As a result of fixing issue 37 in API, we have an issue in that the translation using i18next is not working when done inside the exported function getPageHeader() , now we have to find a solution to do it outside of it.

**Comment by martinheppner** [comment]
Where can I see the problem? Can we deploy on UAT? I would like to know if there is a decision to be made, or if it just a statement, that a solution has to be found. I would like to understand why this topic is now in existance. 

Sorry for so many questions. :-)

**Comment by Falsal** [comment]
I updated UAT already with the version before fixing this issue,  so now
there are 2 untranslated titles for the list of links (cities and regions
lists on Start page),
the issue is that this translation that happens deep in the call stack
seems to interfere with the rendering of the start page components, related
to the issue #37 api which Abdul and I just finished debugging. (showing
the maintenance page when total_tours = 0)

**Comment by martinheppner** [comment]
Are we talking about this?

![20231013_093940.jpg](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/44efc4c2-6911-41cf-95ef-d098f6b2257c)

**Comment by martinheppner** [comment]
Can we aim for this: https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=41439302 ?

**Comment by Falsal** [comment]
@martinheppner : yes we can go for 216 , so I will put this issue (215) to sleep now
