### ISSUE TITLE
Kartenansicht-2 : create floating button

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#219]
Introduce "Kartenansicht" as shown on

Dev-Infos-Mobile:
https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=34%3A6220&mode=design&t=AcMi6WSLBYCbqLI8-1

Dev-Infos-Desktop:
https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=330%3A12679&mode=design&t=AcMi6WSLBYCbqLI8-1

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/ae35fca3-ee37-481b-be2d-2d815b23fc9e)


![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/6df2c460-b0df-44a4-be65-6c325f1b863e)

**Comment by Falsal** [comment]
@martinheppner :
please export a new set of language json files (see the new key "zur_kartenansicht"

**Comment by Falsal** [comment]
Created 2 buttons, one for the start page and one for toggling the map within the results page

**Comment by Falsal** [comment]
completed in dev branch
