### ISSUE TITLE
Error handelling when no tour is found in the backend

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#226]
this is related to the api /issue #6
As the client side gets the response including a 404 error, we need to redirect to the start page

**Comment by Falsal** [comment]
completed

**Comment by Falsal** [comment]
Suggested behaviour for start page, when clicked on a tour card:

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/00edf2f6-f441-4f96-9a01-8b375a796b6a)

**Comment by martinheppner** [comment]
Why would we show a tile if it is not available? How would that be possible? How can this case even occur?

I do not like this solution. Sorry.
