### ISSUE TITLE
PDF / GPX download condition

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#23]
The buttons PDF and GPX download should only be active, when the visitor has already selected his city. If not, the click on either of PDF or GPX button should be possibly, but should open up first an overlay, asking the visitor to select his or her city. See #24

**Comment by martinheppner** [comment]
Version 3: Mobile & Desktop: https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0

**Comment by FALBZB** [comment]
This is already done by external guy; i.e. a whole page overlay comes up when user attempts to go to detail page without a city being selected. But currently it has a bug. 
A list of bugs for "post Header-design" has been made.
