### ISSUE TITLE
Translation of header text on main coming from city links in start page

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#246]
As follow up on issue #217

**Comment by Falsal** [comment]
@martinheppner : please translate the last 2 lines inside the excel sheet

**Comment by martinheppner** [comment]
> @martinheppner : please translate the last 2 lines inside the excel sheet

Where is this used? What was used before that?

**Comment by Falsal** [comment]
task completed

@martinheppner : i replaced "cityCap" with city.label inside the google sheet

**Comment by martinheppner** [comment]
What is cityCap? Where did you place it exactly? Is there something to do now?
