### ISSUE TITLE
No pdf generation on UAT , but generates on localhost

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#253]
Just checked , It hasn't been working in UAT for a while now,   as it is functioning on my local environment, it should be an issue of the hosting server.

**Comment by martinheppner** [comment]
That may be. The question is: What is the difference? On production it seems not to work either.

Maybe this is a similar problem like with the share button?

As production is affected, I am increasing the priority of this ticket.

**Comment by Falsal** [comment]
@martinheppner :
I am getting an error as follows on UAT:

_Failed to load resource: the server responded with a status of 404 (Not Found).    119.bundle.js:102_ 

a possible clue to what the problem could be:

File :  sync.js
Line 64 /     let proddevPath = "../";
Question: is this the correct path or we need a level up ?
