### ISSUE TITLE
Show Heimatbahnhof in Searchmask

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#262]
If the search field is clicked, the search entry mask is shown. The title is currently just "Suche". 

Maybe it would be beneficial if the line would show the Heimatbahnhof, too? See screenshot:
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/3d2d2f51-3a27-4c7a-8446-fd7fc1f3ba40)

Optional: The text of the Heimatbahnhof could be a link, which gives the possibility to switch to the mask to change the Heimatbahnhof.

**Comment by martinheppner** [comment]
I added to the translation tables the field "start.ab_heimatbahnhof". This should be in front of the selected city.

I found already one of the positions, where this has to be added - Search.js line 841 - but I am not able to add it without error message.


```
{pageKey !== "detail" ? (
                    <span className="search-bar--city">
                      {cityInput.length > 0
                        ? **cityInput**
                        : t("start.heimatbahnhof")}
                    </span>
                  ) : !cityInput && pageKey === "detail" ? (
                    <Box
                      className="search-bar--city"
                      sx={{
                        cursor: "pointer",
                        color: "#4992FF !important",
                        fontFamily: `"Open Sans", "Helvetica", "Arial", sans-serif`,
                        fontSize: { xs: "14px", sm: "15px" },
                        fontWeight: "700",
                        lineHeight: "20px",
                      }}
                    >
                      {t("search.waehle_dein_heimatbahnhof")}
                    </Box>
                  ) : (
                    <Box className="search-bar--city">{cityInput}</Box>
                  )}
```

**Comment by Falsal** [comment]
@martinheppner : will get back to you on this shortly

**Comment by Falsal** [comment]
Is this what is meant ?




![Image](https://github.com/user-attachments/assets/86f5fe78-2bcb-453d-9798-e20a79faef13)

**Comment by martinheppner** [comment]
The selected city should get the text in front of the city name: "ab Linz", "ab Wien" - instead of only "Linz" or "Wien"

![Image](https://github.com/user-attachments/assets/3326c2fa-1595-49fb-9623-4d6bbe73a3d4)

**Comment by Falsal** [comment]
Ok, done , here how it looks now:


![Image](https://github.com/user-attachments/assets/080d49f8-f39b-4b34-9e7d-46038f41e0d9)





![Image](https://github.com/user-attachments/assets/f3b174d1-562f-4c4b-937b-0f734434e293)
