### ISSUE TITLE
Fwd: [kontakt] Eingeschränkte Bedienungsmöglichkeiten am iPhone/iPad über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#273]
Von: 'René Brunner' via kontakt@bahn-zum-berg.at <kontakt@bahn-zum-berg.at>
Date: Do., 11. Jän. 2024, 10:53
Subject: [kontakt] Eingeschränkte Bedienungsmöglichkeiten am iPhone/iPad
To: <kontakt@bahn-zum-berg.at>

Guten Tag!

Auf dem iPhone und iPad funktioniert zuugle scheinbar nicht richtig. Sowohl
in Safari als auch in Firefox kann ich zwar die Suche und Filter anwenden,
aber dann passiert nichts, wenn ich auf eines der Suchergebnisse tippe.
Auch bei Firefox am PC ist das so.
Seit wann das so ist, kann ich nicht sagen, da ich länger nicht auf der
Seite war. Es hat aber schon mal funktioniert.

Freundliche Grüße
René Brunner

Von meinem iPad gesendet

Attachments (0):

**Comment by martinheppner** [comment]
@veronikaschoell du nutzt ja ein iphone, oder? Kannst du das bitte testen, was René hier beschreibt?

**Comment by martinheppner** [comment]
Am Windows PC mit Firefox kann ich Ergebnisse sehen und filtern. Der URL https://www.zuugle.at/suche?city=amstetten&search=schnee&filter=%7B%22coordinatesSouthWest%22%3A%5B%5D%2C%22coordinatesNorthEast%22%3A%5B%5D%2C%22singleDayTour%22%3Atrue%2C%22multipleDayTour%22%3Atrue%2C%22summerSeason%22%3Atrue%2C%22winterSeason%22%3Atrue%2C%22traverse%22%3Afalse%2C%22difficulty%22%3A10%2C%22minAscent%22%3A0%2C%22maxAscent%22%3A2264%2C%22minDescent%22%3A0%2C%22maxDescent%22%3A500%2C%22minTransportDuration%22%3A0.62%2C%22maxTransportDuration%22%3A4.45%2C%22minDistance%22%3A0%2C%22maxDistance%22%3A46.85%2C%22ranges%22%3A%5B%22Alpenvorland%22%2C%22Ankogelgruppe%22%2C%22Bayerische+Voralpen%22%2C%22Berchtesgadener+Alpen%22%2C%22Brandenberger+Alpen%22%2C%22Chiemgauer+Alpen%22%2C%22Ennstaler+Alpen%22%2C%22Goldberggruppe%22%2C%22Gurktaler+Alpen%2C+Nockberge%22%2C%22Gutensteiner+Alpen%22%2C%22Hochschwabgruppe%22%2C%22Kaisergebirge%22%2C%22Karpaten%22%2C%22Kitzb%C3%BCheler+Alpen%22%2C%22Lavanttaler+Alpen%22%2C%22M%C3%BChlviertel%22%2C%22M%C3%BCrzsteger+Alpen%22%2C%22Nieder%C3%B6sterreich%22%2C%22Ober%C3%B6sterreichische+Voralpen%22%2C%22Randgebirge+%C3%B6stlich+der+Mur%22%2C%22Rax-Schneeberg-Gruppe%22%2C%22Rottenmanner+und+W%C3%B6lzer+Tauern%22%2C%22Salzburger+Schieferalpen%22%2C%22Salzkammergut-Berge%22%2C%22Schladminger+Tauern%22%2C%22Seckauer+Tauern%22%2C%22Totes+Gebirge%22%2C%22T%C3%BCrnitzer+Alpen%22%2C%22Waldviertel%22%2C%22Wienerwald%22%2C%22Ybbstaler+Alpen%22%2C%22Zillertaler+Alpen%22%5D%2C%22types%22%3A%5B%22Bike+%26+Hike%22%2C%22Hochtour%22%2C%22Klettersteig%22%2C%22Langlaufen%22%2C%22Schneeschuh%22%2C%22Skitour%22%2C%22Wandern%22%5D%2C%22languages%22%3A%5B%22de%22%5D%7D zeigt mir untenstehendes Ergebnis an:



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/77c065c5-591a-43ec-acc7-8662af0645a9)

**Comment by veronikaschoell** [comment]
Ich lade dir mein Suchergebnis in Screenshots hoch - ich hoffe ich habe richtig verstanden was Rene meint. 

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/134488225/edf06b36-4e4e-4f97-8695-6b9cb1c2f5bb)



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/134488225/abf03792-9d8b-4ed4-bdcc-a9f787024897)



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/134488225/a9d62f7e-a3f2-42c7-99da-a1244c4e09a3)



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/134488225/db1cf97b-a827-43ba-adad-8716a23d0cff)

**Comment by veronikaschoell** [comment]
Möglicherweise liegt das am aktivierten Pop-up Blocker, bei mir i phone 14, safari ios 17.2.1.

**Comment by martinheppner** [comment]
@Falsal have we got a problem with a new pop-up blocking strategy on iPhones and iPads?

**Comment by martinheppner** [comment]
Changed from Javascript window.open to html anchor link
