### ISSUE TITLE
Same Link produces different results on Chrome and on Firefox

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#274]
Link: https://www.zuugle.at/suche?city=wien&filter=%7B%22coordinatesSouthWest%22%3A%5B%5D%2C%22coordinatesNorthEast%22%3A%5B%5D%2C%22singleDayTour%22%3Atrue%2C%22multipleDayTour%22%3Afalse%2C%22summerSeason%22%3Atrue%2C%22winterSeason%22%3Atrue%2C%22traverse%22%3Afalse%2C%22difficulty%22%3A10%2C%22minAscent%22%3A0%2C%22maxAscent%22%3A3000%2C%22minDescent%22%3A0%2C%22maxDescent%22%3A3000%2C%22minTransportDuration%22%3A0.03%2C%22maxTransportDuration%22%3A5.57%2C%22minDistance%22%3A0%2C%22maxDistance%22%3A80%2C%22ranges%22%3A%5B%22Alpenvorland%22%2C%22Ankogelgruppe%22%2C%22Bayerischer+Wald%22%2C%22Berchtesgadener+Alpen%22%2C%22Brandenberger+Alpen%22%2C%22Burgenland%22%2C%22B%C3%B6hmerwald%22%2C%22Chiemgauer+Alpen%22%2C%22Dachsteingebirge%22%2C%22Ennstaler+Alpen%22%2C%22Goldberggruppe%22%2C%22Gurktaler+Alpen%2C+Nockberge%22%2C%22Gutensteiner+Alpen%22%2C%22Hausruck%22%2C%22Hochschwabgruppe%22%2C%22Kaisergebirge%22%2C%22Karpaten%22%2C%22Karwendel%22%2C%22Kitzb%C3%BCheler+Alpen%22%2C%22Kreuzeckgruppe%22%2C%22Lavanttaler+Alpen%22%2C%22Loferer+und+Leoganger+Steinberge%22%2C%22Mangfallgebirge%22%2C%22M%C3%BChlviertel%22%2C%22M%C3%BCrzsteger+Alpen%22%2C%22Nieder%C3%B6sterreich%22%2C%22Ober%C3%B6sterreich%22%2C%22Ober%C3%B6sterreichische+Voralpen%22%2C%22Radst%C3%A4dter+Tauern%22%2C%22Randgebirge+%C3%B6stlich+der+Mur%22%2C%22Rax-Schneeberg-Gruppe%22%2C%22Rottenmanner+und+W%C3%B6lzer+Tauern%22%2C%22Salzburger+Schieferalpen%22%2C%22Salzkammergut-Berge%22%2C%22Schladminger+Tauern%22%2C%22Seckauer+Tauern%22%2C%22Sengsengebirge%22%2C%22Stubaier+Alpen%22%2C%22Tennengebirge%22%2C%22Totes+Gebirge%22%2C%22T%C3%BCrnitzer+Alpen%22%2C%22Waldviertel%22%2C%22Wien%22%2C%22Wienerwald%22%2C%22Ybbstaler+Alpen%22%2C%22Zillertaler+Alpen%22%5D%2C%22types%22%3A%5B%22Bike+%26+Hike%22%2C%22Hochtour%22%2C%22Klettern%22%2C%22Klettersteig%22%2C%22Langlaufen%22%2C%22Rodeln%22%2C%22Schneeschuh%22%2C%22Skitour%22%2C%22Wandern%22%2C%22Weitwandern%22%5D%2C%22languages%22%3A%5B%22XX%22%2C%22de%22%2C%22en%22%2C%22it%22%5D%7D

**Result on Chrome and on Firefox:**
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/8f572399-57eb-417d-b739-725b9afc6985)

**Comment by Falsal** [comment]
@martinheppner : not true on my end, see the screenshot of firefox below:
When i used one item to filter , i also got the same result for both browsers, was it a particular filter combination ?


![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/37c2c805-e641-4657-9897-568ea3d0678e)

**Comment by Falsal** [comment]
cannot upload my screenshot , will send it by email

**Comment by martinheppner** [comment]
Changed from Javascript window.open to html anchor link
