### ISSUE TITLE
Evaluate reloading Detail page at first load

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#277]
For a sec or less, the page shows first the content without data, then reloads with data, it doesn't seem to be a good UX , so lets evaluate how to improve on it, if we want to .

**Comment by Falsal** [comment]
work done in this issue : I have included a spinner on the whole page, but it still shows the first unloaded page.

**Comment by replyre** [comment]
IS this issue still open?

**Comment by martinheppner** [comment]
Yes, it is

**Comment by replyre** [comment]
okay, I would like to contribute.

In brief, you wish to have a loader until the data is completely loaded. right?

**Comment by Falsal** [comment]
yes, but also minimise the number of page-reloads .

**Comment by martinheppner** [comment]
> okay, I would like to contribute.
> 
> In brief, you wish to have a loader until the data is completely loaded. right?

@replyre That's great. At the moment someone is already working on it. I mistook you for him yesterday.

What we would need very urgently is this: https://github.com/bahnzumberg/zuugle-suchseite/issues/182
Do you think you could take a look at that?

**Comment by replyre** [comment]
@martinheppner, okay I will look into it ?
