### ISSUE TITLE
Filter multipleDayTour greift nicht über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#281]
Von: Gerold Petritsch (BzB) 
https://www.zuugle.at/suche?city=bruck&filter=%7B%22coordinatesSouthWest%22%3A%5B%5D%2C%22coordinatesNorthEast%22%3A%5B%5D%2C%22singleDayTour%22%3Afalse%2C%22multipleDayTour%22%3Atrue%2C%22summerSeason%22%3Atrue%2C%22winterSeason%22%3Afalse%2C%22traverse%22%3Afalse%2C%22difficulty%22%3A10%2C%22minAscent%22%3A0%2C%22maxAscent%22%3A3000%2C%22minDescent%22%3A0%2C%22maxDescent%22%3A3000%2C%22minTransportDuration%22%3A0.02%2C%22maxTransportDuration%22%3A5.82%2C%22minDistance%22%3A0%2C%22maxDistance%22%3A80%2C%22ranges%22%3A%5B%22Rax-Schneeberg-Gruppe%22%5D%2C%22types%22%3A%5B%22Hochtour%22%2C%22Wandern%22%2C%22Weitwandern%22%5D%2C%22languages%22%3A%5B%22XX%22%2C%22de%22%2C%22en%22%2C%22it%22%2C%22sl%22%5D%7D

-- 
Gerold Petritsch
*Verein Bahn zum Berg*
ZVR: 1112324997

Bahn-zum-Berg.at <https://bahn-zum-berg.at>
www.zuugle.at <https://www.zuugle.at>
t: +43(0)650 2073 866
Attachments (0):

**Comment by martinheppner** [comment]
Actually the link breaks Zuugle. Why?

**Comment by martinheppner** [comment]
There are tours which have a duration more than 1 day. The filter does not filter exclusively on these tours.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/16aa8e72-a500-43dd-b66d-c89124274471)

```
SELECT
*
FROM tour
WHERE number_of_days>1
AND range_slug='hochschwabgruppe'
LIMIT 10
```

**Comment by Falsal** [comment]
The types of data received are not string values for multipleDayTour, singleDayTour anymore, so it seems the type has been changed in the database from string values to Boolean. 
This issue is also repeated for winterSeason and summerSeason, 
both cases above have been corrected.
