### ISSUE TITLE
Itinerary detail 2: suchseite / Translation

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#286]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/87718607/5373da51-b5ac-4388-99e3-bbd543052a80)

Translate Itinerary based on JSON

**Comment by martinheppner** [comment]
Please contact the persons I am listing in my email to you (in separate mails, to not show the email addresses to one another) and ask them to test the translations on www2.zuugle.at. I suggest creating a shareable link and send this, together with a screenshot, where the passages which should be checked are highlighted.

**Comment by Falsal** [comment]
Translation of itinerary completed, 
remaining : contact translation "persons" as required by Martin.
create a new issue to fix the translation table entries which have either had errors or have been altered during work on the code.
