### ISSUE TITLE
UAT bug: "departureText" is not receiving correct departure / arrival date

### ISSUE THREAD

**Issue by FALBZB** [bahnzumberg/zuugle-suchseite#288]
UI in the UAT : 
the function getDepartureText creates the text for the itinirary detail for one way connection (either to or from tour).
The issue : we are not getting the correct values for " connection_arrival_datetime " nor for "connection_departure_datetime".

**Comment by martinheppner** [comment]
Can you please provide a sql query to show the problem with a limited amount of tours?

**Comment by Falsal** [comment]
@martinheppner : 
below is a translation of a knex call in the API /tours.js > connectionWrapper > query_con. (with a 10 limit)
SELECT * FROM fahrplan
WHERE hashed_url = 'your_hashed_url_value'
  AND tour_provider = 'your_tour_provider_value'
  AND city_slug = 'your_city_slug_value'
LIMIT 10;

**Comment by Falsal** [comment]
example i have : 
hashed_url = '10198'
tour_provider = ""bahnzumberg"
city_slug = "wien"
