### ISSUE TITLE
Same code works on www2 and fails on www

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#289]
We deployed the code from UAT (www2.zuugle.at) to PROD (www.zuugle.at). So it is the same code. Node.js version and pm2 version are identical. The only obvious difference is the two installations use different databases. The amount of data on UAT is significant smaller than on PROD.

The SQLs are tested identical and if queried onto the two PostgreSQL databases return valid results without SQL error. Speed seems to be ok in both.

- Calling https://www2.zuugle.at/suche?city=amstetten on UAT returns results.
- Calling https://www.zuugle.at/suche?city=amstetten on PROD does not.

On PROD the console throws this error:
`{
    "message": "timeout of 60000ms exceeded",
    "name": "AxiosError",
    "stack": "AxiosError: timeout of 60000ms exceeded\n    at c.ontimeout (https://www.zuugle.at/app_static/496.bundle.js:102:966648)\n    at je.request (https://www.zuugle.at/app_static/496.bundle.js:102:971409)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 60000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "authorization": "FV69pR5PQQLcQ4wuMtTSqKqyYqf5XEK4"
        },
        "baseURL": "https://www.zuugle.at/api",
        "params": {
            "city": "wien",
            "range": null,
            "state": null,
            "country": null,
            "type": null,
            "search": null,
            "filter": {},
            "sort": null,
            "provider": null,
            "map": null,
            "domain": "www.zuugle.at",
            "currLanguage": "de"
        },
        "method": "get",
        "url": "tours/"
    },
    "code": "ECONNABORTED",
    "status": null
}`

The website is always doing a reload: First it shows "0 results", then it is doing a reload, which leads normally to a result. The reload is not desired beheauvior.

### UAT - www2.zuugle.at
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/3093221c-df90-4442-9799-af96e2701414)

### PROD - www.zuugle.at
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/a2e901a0-417a-4ed6-82c0-97971cc0f147)

**Comment by martinheppner** [comment]
Install Guideline API: https://github.com/bahnzumberg/zuugle-api?tab=readme-ov-file#zuugle-api
Install Guideline Frontend: https://github.com/bahnzumberg/zuugle-api?tab=readme-ov-file#zuugle-api

**Comment by martinheppner** [comment]
Update 28.02.2024: https://www.zuugle.at/suche?city=amstetten works again, as it loads results immediately. What the page still does: Show first 0 results and do a complete reload afterwards.

**Comment by martinheppner** [comment]
If solved, please close https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=50413467 as well.

**Comment by martinheppner** [comment]
I restored the PostgreSQL database of 26th of February 2024, when this problem occured first. 

- A first analysis of the data did not return anything.
- Second attempt was to use the identical SQL which is used by the application directly on the databse. No error.
- Third attempt: I pointed my local development to the restored database. API immediately crashed in function "prepareTourEntry" - see screenshot.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/997c9ae2-102d-43c5-9c8f-8596807b2e50)

I out a try-catch around this code, which prevents the crashing. Now you can see, that on Monday 26th of February not all datasets of table "fahrplan" have been transmitted.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/34d15054-b084-4cd3-8654-81a50ac6f15d)

We have to think about countermeasures and an alerting in such cases.

**Comment by martinheppner** [comment]
Follow up task: https://github.com/orgs/bahnzumberg/projects/2?pane=issue&itemId=55152389

**Comment by Falsal** [comment]
Reference to "the counter measure":  in case of no data available or partial data missing for a certain tour we can of course raise a flag that goes to the client-side and there we can insert some alerting text in the card .

**Comment by martinheppner** [comment]
That is possible. I rather do not want to show it on the front end, but create an issue on GitHub.
