### ISSUE TITLE
Translation for hm, km, hm, min etc.

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#291]

**Comment by martinheppner** [comment]
- [ ] Prepare spreadsheet
- [ ] Fill in quick translations
- [ ] Implement code
- [ ] Ask for quality check with native speakers

**Comment by Falsal** [comment]
@martinheppner please go ahead with step 2 above; fill quick translations

**Comment by martinheppner** [comment]
Attached in a zip file are the json translation files: 
[json.zip](https://github.com/bahnzumberg/zuugle-suchseite/files/14875815/json.zip)

**Comment by Falsal** [comment]
completed step 3
