### ISSUE TITLE
Kartenansicht-2 : Show map

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#298]
This related to #219 : floating button
purpose to activate the button so that the map can be viewed on the Main.js

**Comment by Falsal** [comment]
@martinheppner : I have the following questions:  (first one is unclear for me even when looking at the Figma)

A)  normal user behavior: 
at start page : 
                     a map button is visible: when clicked, adds a param "map"= true, the map can be toggled and shows the clusters with total number of tours (figure changes if a city is selected).
user clicks on GO button:
                     the url already has a param "map"= true and this activates the map view when moving to the results page. (if no map= true in url then no map will be visible at results page)
user at results page :
                      same behavior as in Start page and when clicking on the back button .

Please confirm or add your feedback to (A)

B) regarding the url param for map variables (), 
                      current version : 
        filter=%7B"coordinatesSouthWest"%3A%7B"lat"%3A46.01222384063236%2C"lng"%3A10.7830810546875%7D%2C"coordinatesNorthEast"%3A%7B"lat"%3A49.2140089056539%2C"lng"%3A17.462768554687504%7D%7D

                     new version: 
                     &sw-lat=46.012223&sw-lon=10.783081&ne-lat=49.214008&ne-lon=17.462768

Please confirm or add your feedback to (B)

**Comment by Falsal** [comment]
results of the phone discussion  (Martin & Faris):
Regarding question B: the new version for the map params is confirmed now. (this is related to another open issue)

Regarding A:
The understanding of Martin's feedback: 
1. the map should always be there on the page and that means that the button would only toggle to the map section or to the tours "tiles" section when clicked.
2. point 1  goes for Start page and results page ??
3. the map should be a new method for filtering tours (geo-filtering ?).
4. As a consequence to point 3: The first time we get to a page the total number of results mentioned on the page in text (ex. 55 tours) should be reflected on the map (total number of markers/clusters)
5. Also as a consequence to point 3: when map is zoomed in ; the total number in the text should reflect the number reached on the map (ex. 35 tours), meanwhile the number inside the tiles should remain at 9 until user scrolls down and reaches a maximum of 35 tour tiles. 

@martinheppner , please review the Figma and just make sure that these statements above are what we need to implement  (the Figma version 3 shows button only on the start page (takes you to results page WITH a map), while the GO button takes you to the results page but WITHOUT map, otherwise please make your changes in the comments section below.

Figma : https://www.figma.com/proto/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=330-12679&t=WnTE7hRkDVgP1TmP-0&scaling=scale-down&page-id=110%3A5678&starting-point-node-id=110%3A5679 

Anyway, lets discuss if inside this issue#298 we should have all of the above items included.

**Comment by martinheppner** [comment]
Yes, this is how I understood Stefans thinking.

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/8f822215-d98e-4fd8-9f0b-449c907a109a)

**Comment by Falsal** [comment]
The discussion results about the current options for map's markersList API calls.
we agreed to go for a separate call for the 3 columns id along with coordinates for position of arrival location

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/1d4e6450-6250-487c-9625-d4f29c4d8698)

**Comment by Falsal** [comment]
@martinheppner : please provide the translation for "zur_kartenansicht"   and one for "remove map" in lines 229 and 230 in the translation shet
