### ISSUE TITLE
sport type "Bike & Hike" does not show on Tour Card or on detail page

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#299]

**Comment by martinheppner** [comment]
Hint: PHP approach https://stackoverflow.com/questions/1873793/html-encode-in-php

**Comment by Falsal** [comment]
Hint: countFilterActive() needs to be reset in a cleanup action after unmounting component.

**Comment by Falsal** [comment]
Completed : actually issue were a couple of things : a mismatch of the translation key with the keys stored in the utility function. So the "&" must be replaced with the "_" that is used in the translation key.
