### ISSUE TITLE
Detail Page - Translations

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#30]
Translation in some places (e.g. “Öffi-Fahrplan”, “Für diesen Tag wurden keine Verbindungen gefunden.”, metrics of the Tour details, …)

**Comment by FALBZB** [comment]
done BUT, in the Share buttons the translated text is in some languages too long for the space, either we have an increase in the length of the text field or we shorten the language text.

**Comment by FALBZB** [comment]
I created a function inside utilities file globals.js and imported it in DetailReworked.js and used the function in 2 button texts that showed overflow , we can reuse this function in any other situation, for now i see only the buttons as an issue. In the mobile version it stacks two lines above each other.
