### ISSUE TITLE
URL with filter does not do the job

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#304]
Calling the URL https://www2.zuugle.at/suche?city=bruck&filter=%7B%22coordinatesSouthWest%22%3A%5B%5D%2C%22coordinatesNorthEast%22%3A%5B%5D%2C%22singleDayTour%22%3Afalse%2C%22multipleDayTour%22%3Atrue%2C%22summerSeason%22%3Atrue%2C%22winterSeason%22%3Afalse%2C%22traverse%22%3Afalse%2C%22difficulty%22%3A10%2C%22minAscent%22%3A0%2C%22maxAscent%22%3A3000%2C%22minDescent%22%3A0%2C%22maxDescent%22%3A3000%2C%22minTransportDuration%22%3A0.02%2C%22maxTransportDuration%22%3A5.82%2C%22minDistance%22%3A0%2C%22maxDistance%22%3A80%2C%22ranges%22%3A%5B%22Rax-Schneeberg-Gruppe%22%5D%2C%22types%22%3A%5B%22Hochtour%22%2C%22Wandern%22%2C%22Weitwandern%22%5D%2C%22languages%22%3A%5B%22XX%22%2C%22de%22%2C%22en%22%2C%22it%22%2C%22sl%22%5D%7D on UAT does not execute the filter immediately. But given the filter in the URL, there is no reason why it should only fire after a new fresh.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/62b2bea5-86ba-4a6e-b375-2a75dfa7b93f)

**Comment by Falsal** [comment]
done
