### ISSUE TITLE
Use variable code for calling icons

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#307]
Symbols are called by german names instead of variable code

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/799631b5-f4fb-4ab6-9f8c-ad752d8407b4)

**Comment by martinheppner** [comment]
Please start to analyse src/components/TimeLine/utils.js the function getIconFromText

**Comment by Falsal** [comment]
completed within the dev while issue #298
