### ISSUE TITLE
Slug in Heimatortfeld

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#308]
Calling the URL https://www2.zuugle.at/tour?city=st-johann-in-tirol&search=Schneealm

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/e5c29430-c7f9-41dd-80c6-d44307332661)

Green: How it should be
Red: Not OK

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/bdcfcb66-f905-4d0a-8643-e1d1a93c2b79)

**Comment by Falsal** [comment]
completed
