### ISSUE TITLE
Detail Page - Itinerary (Calendar)

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#31]
o	Styling for arrival (“Anreise”)
o	Tour-duration info
o	Returns (“Rückreisen”)

Not in scope of this issue: Links to external sites (eg. ÖBB)

**Comment by martinheppner** [comment]
Version 3: Mobile & Desktop: https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0



![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/123db39e-8d06-4e90-ade7-7da278d24578)

**Comment by FALBZB** [comment]
despite that there are differences with the figma, the current design provided by the externals fits the data inside the available space . If no objections, i will consider this issue completed.
