### ISSUE TITLE
change url for map params

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#314]
- use lat, lon instead of current lng 
- Shorten the param names from coordinatesSouthWest"%3A%7B"lat"%3A45.17434025381658%2C"lng"%3A4.218411610190387%7D%2C"coordinatesNorthEast"%3A%7B"lat"%3A49.43245661268574%2C"lng"%3A20.060696766440387%7D%7D
- Should be s=45.174340&w=4.218411&n=49.432456&e=20.060696

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/4b51a797-5bb3-40a8-bc3c-2f67754616e9)
