### ISSUE TITLE
pdf : smaller maps below main one sometimes show default "London" map

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#316]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/17b3e906-c13c-4495-9564-6188a2a3eaf7)

**Comment by Falsal** [comment]
Use a default picture if image is not created successfully, find out which picture to replace the current London map with.

**Comment by martinheppner** [comment]
PDF feature has been deactived, so this issue will not be implemented.
