### ISSUE TITLE
Show id in URL www.zuugle.at/tour?city=wien

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#317]
The tour id (not the hashed_url) should be shown in the URL like https://www.zuugle.at/tour?id=123&city=wien (only on Detailpage).

**Comment by martinheppner** [comment]
On this Detailpage the id should be shown in the URL. The goal is, that I can go back to this page whenever I call it like  https://www.zuugle.at/tour?id=123 or  https://www.zuugle.at/tour?id=123&city=wien

In this case the itinerary of today is shown. The functionality of the disposal id is untouched and still working (e.g. https://www2.zuugle.at/tour?share=b68954fd-3fda-4e2f-87e9-57508bc98300).

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/235dddc9-7b90-48e6-be2f-e393686832a7)

**Comment by martinheppner** [comment]
- [ ] Mandatory is the parameter "id"
- [ ] Optional is the parameter "city"
- [ ] Optional parameter "share"
- [ ] No other paramter is used

**Comment by Falsal** [comment]
done
