### ISSUE TITLE
Detail Page - Design

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#32]
o	Fallback images (for map and tour image, see Figma “Fallback” section)
o	“Öffi-Fahrplan” button in mobile view
o	Styling for download buttons, when no connection was found for the selected day (currently, the buttons are not clickable and a error message is displayed down below)
o	Testing of the design with long strings (for example: What happens if a value is so long that it has to be in a new line, does it break the design?)
o	Testing fallback cases (what if one field is empty, is it displayed correctly in the UI?)

**Comment by martinheppner** [comment]
Version 3: Mobile & Desktop: https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0

**Comment by FALBZB** [comment]
lets go over it to see what is missing , if anything
