### ISSUE TITLE
remove use of some fahrplan columns

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#323]
1. remove use of **valid_thru** from frontend. When this is done and secured, valid_thru has to be removed from api is well: https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=60762642
2. remove use of **weekday_type**

**Comment by Falsal** [comment]
1. valid_thru in suchseite was completed earlier
1. valid_thru: in API  completed in issue#103
3. weekday_type API: replaced the use of column named "weekday_type" with a change in the query that uses the name "weekday_type". see commit : https://github.com/bahnzumberg/zuugle-api/commit/fec8bd414278b6aade88425919f6d3073c9a7819
