### ISSUE TITLE
Fix search on frontend

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#331]
sometimes we do not get the right results, when we have the map (tested on production), is it due to FE issues ?
Remarks: 
not stable results: for example when searching for "schneeberg" with city = "amstetten"
PROD :  first attempt: on Start page pressing GO will give 0 total and no tiles.
               from Main page: doing the same selection will give us a certain total and tiles which all seem to be the right ones.
               after doing the step with Main page the 

Dev/prod database: 

UAT / smaller database

sometimes (when ?) the search with "silvester / amstetten" : produces 0 total but some tiles below it that are NOT the correct ones for the selection (see that by the default pic and when you open the detail page).

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/4cf65001-bf6e-4e76-835a-2d69bb918460)

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/3b4fc148-8461-4c31-b1aa-c360a9f84d30)

**Comment by martinheppner** [comment]
Possible way to find out the multiple queries:

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/7d334904-73aa-470b-842c-2d45677b228f)

**Comment by Falsal** [comment]
Discoveries :
We checked the generated sql quarries and compared them with the expected results and they seem to match,  at some cases the FE shows mismatched results. here are they:

- [ ] The total tours is the main reference point. Remedy: the totalTours is now condition on the render of maps + MapBtn + CardContainer, i also added a no card text NoCards component . Requested after Friday meeting: remove the NoCards to limit the totalTours = 0 to card container meaning; if o totalTours then ONLY empty map will show 
- [ ] Search giving actual results PLUS remains of other tours :  example with Innsbruck and "weg" as search term. The result on fast network page is 3 only (after multiple renders) where as on slow page it shows the 3 results followed with more cards from previous render of total cards. Remedy: the re-renders issue #330 seems to be causing unnecessary calls to the backend and showing temp views. Currently searching for temporary solution for that.

**Comment by Falsal** [comment]
done
