### ISSUE TITLE
Map button not on same level

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#336]
Button is in Startpage hugher positioned as on Resultpage - see screenshots below

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/055404b0-4d1e-4692-a977-9537a1727be2)

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/42d01d01-9c5c-495f-be44-c90739205acc)

**Comment by martinheppner** [comment]
Reduce height of blue header?

**Comment by Falsal** [comment]
completed but need to make the height of "totalToursHeader" less to meet the figma standards
