### ISSUE TITLE
Show content of popup in map

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#339]
Same as tile: Multi language, etc.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/6ce622ca-c523-4d86-8f66-29b7aa7f69a0)

Attention: Please do not invest to much time into styling. We will rework all the tiles anyhow at a later time. Just "close" to the image.

**Comment by Falsal** [comment]
Option to fix this: adjust the component CardTour to be able to match the image above and add it to the Map Popups.

**Comment by Falsal** [comment]
This is complete but only styled for the desktop, another issue is needed to style it for mobiles (responsive design)
