### ISSUE TITLE
Cleanup of old code and files

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#34]
Remove old code and delete files, which are not used anymore.

Bearingpoint wrote: "Cleanup of old code and files (we did not delete the old files intentionally so there is a possibility to switch back while the new design is not yet finished)"

**Comment by Falsal** [comment]
Task completed.

questions:
1) file seoPageHelper , do we activate the range links in start page? currently we have only citylinks, I activated it, please check.
2) file named backListener.js is not being used anywhere, but it is a good example for a functionality we would need to use in the near future.

**Comment by Falsal** [comment]
remaining to be cleaned : parts of components folder

**Comment by martinheppner** [comment]
We will only link on cities, but no startpage for ranges.

**Comment by Falsal** [comment]
@martinheppner :
Removed range links on start page.
cleaned up all except a few marked files to check together, make sure we will not need them in the near future.
