### ISSUE TITLE
Webpack : size of build is too large for github Action

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#340]
After intro of the package styled-components I started getting oversized build file, 
I removed some code from the SVG files and now will remove the package to check if it works now.

**Comment by martinheppner** [comment]
Which SVG files? They are tiny. Please get rid of the additional package, when you know already that this breaks the build. Our code is bloated enough. Why would we want to add more?

**Comment by Falsal** [comment]
We talked about this on our Monday meeting, I explained everything to you then.

**Comment by martinheppner** [comment]
You pointed out your view. I did not share it on Monday and I do not share it now.

Which SVG files did you change?

**Comment by Falsal** [comment]
I reverted the commit , the issue was with the package mentioned above, so now we are able to  run a build on dev branch and github actions run as expected.  But still we have a large bundle size as we are getting the warning already in any build we do.

regarding SVG: with the revert there are no changes in the SVG files. Even when i removed a lot of their tags , the svg image on the website did not change or diminish in quality.

Any how, I told you in the meeting that when i used a tool to analyse the build bundle It showed a large size for the SVGs **inside the bundle** , on their own (no bundling) the svg folder has a size of 628KB, the whole build file is 4.8 MB
by the way, , the tool is called webpack-bundle-analyzer , here is a similar question on stackoverflow : https://stackoverflow.com/questions/73548792/webpack-with-svger-causing-huge-bundle-size . 
You can test this tool yourself.

The main message for me was not the SVG alone, but the optimisation that we need to do to our code, we are at the limits of what is acceptable to the build. So another item for optimising our code base is "moment" a package which takes a lot of space , this one we could replace with pure javascript, we use moment as a library in a few places and similar to SVG it showed on the tool to have a large part. Another package is lodash.
A good blog entry on the subject:
https://www.reddit.com/r/reactjs/comments/79i30p/how_much_is_your_production_bundle_size/ 
Ways to begin reducing bundle size:
https://blog.jakoblind.no/3-ways-to-reduce-webpack-bundle-size/

I suggest to create a separate issue for optimisation of the code base.
