### ISSUE TITLE
Lost with 0 results

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#358]
![Screenshot_20240627_113714_Chrome.jpg](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/d4a66605-da4d-4d63-b66a-11e2235c7dfa)

I drilled down to a space, where no hikes are shown. From there I can not do anything anymore - I am lost at an empty map.

The button, to switch back to list, is gone, too.

Only solution is to go back to start page.

I tried to delete all filters - invain.

My expectation would be, that I can zoom out, to see more, or even all hikes I saw before.

**Comment by martinheppner** [comment]
@Falsal this is a bug report for the current sprint

**Comment by Falsal** [comment]
The first version of map filter had bad performance, so I created a new version of the map filter implemented in dev, i moved in it the event handling from the leaflet event handling to a separate useEffect. In this dev version, I have completed this task herewith (#358)

**Comment by Falsal** [comment]
Completed

**Comment by martinheppner** [comment]
Tested. Works now perfect! Not lost anymore. :-)
