### ISSUE TITLE
Itinerary on mobile too wide

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#359]
On my mobile - see screenshot - the itinerary is too wide. Left and right is outside the view size.

https://www2.zuugle.at/tour?id=326&city=amstetten

![Screenshot_20240627_210208_Chrome.jpg](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/d506b0a9-a0bf-44bb-b070-73390ebddbc5)

**Comment by martinheppner** [comment]
This is not only on UAT like that, but on PROD as well. I upgrade the priority therefore to "PROD bug"

**Comment by Falsal** [comment]
Completed but due to lack of connection data this morning, it was not tested.
Branch : dev-detailpage-style

**Comment by Falsal** [comment]
Decided in meeting 15th July :
use the Figma design to make the detail page . See screenshot

![Image](https://github.com/user-attachments/assets/7bce7fb3-58d8-4141-bf68-6241742502f4)

**Comment by Falsal** [comment]
completed
