### ISSUE TITLE
UAT Test: Map loads and disappears again

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#360]
Calling https://www2.zuugle.at/suche?city=salzburg&map=true shows first the map, then reloads and shows blank screen with moving circle.

### Step 1
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/8a125d63-51bb-4398-a126-0c1834ec187f)

### Step 2
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/aee76d82-a981-4f9c-aacb-0e2389f6b4bf)

**Comment by Falsal** [comment]
completed: the UAT api backend was not updated, now it is
