### ISSUE TITLE
Only use bus/train stop marker & always show Zustieg and Rückstieg

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#362]
1. Unify use of markers to bus/train stop, using the same type of markers, color and the same position, showing the bus/railway station. (Martin will provide the new design for markers, he prefers svg)
2. Always draw full track including Zustieg and Rückstieg (On generated images, maps, pdf)

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/d16cb1d3-51ed-4c83-b33f-3a039b460fca)

**Comment by martinheppner** [comment]
I exported the images in PNG format from Figma for start and end (which is from now on always a bus/train stop. The are stored in public\img

Please be advised, that you can call them via url with /app_static/img/startpunkt.png and /app_static/img/zielpunkt.png
This ticket is about showing /app_static/img/startpunkt.png on the maps.

**Comment by Falsal** [comment]
Completed 
Note: to show the different totour and fromtour GPX tracks, i used 2 different colors which can be changed on demand
