### ISSUE TITLE
Bug: Go to map doesn't go to map

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#367]
Once I scrolled down a little (or much) on https://dev.zuugle.at/suche?city=wien, I can press the "Go to map" button - it shows no reaction and certainly no map.

The screenshot shows with the yellow mark, that I scrolled down and pressed then the "Go to map" button.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/21c24b48-eb2b-44fb-9c5f-586e31fa8053)

**Comment by Falsal** [comment]
Fixed
