### ISSUE TITLE
2 x design, 1 x rewrite

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#369]
This description is based on UAT branch: https://github.com/bahnzumberg/zuugle-suchseite/tree/uat Please use this version & branch!

1. Round edges on top of gray area of https://www2.zuugle.at/?city=wien and https://www2.zuugle.at/suche?city=wien (See two pictures below)
2. The width of https://www2.zuugle.at/?city=wien is wider than https://www2.zuugle.at/suche?city=wien and not centered. It should be centered and exactly as wide as https://www2.zuugle.at/suche?city=wien
3. https://www2.zuugle.at/tour/85973/wien should to do the same as https://www2.zuugle.at/tour?id=85973&city=wien and both should work. I tried a little already and put in a reference to a test file in App.js, which has to be removed (Remove \src\views\Main\DetailReworkedMin.js as it was only for testing purpose)

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/5ab42a71-e05b-4239-9209-f82f76e65951)

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/c3bcbf38-c209-4efc-9913-e80a352127f9)

**Comment by uzair-shakeel** [comment]
Bruh the third task links are not working. 

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/144268023/c8c54030-87a7-4ac4-9464-2f4d528fb071)

**Comment by martinheppner** [comment]
Of course the link https://www2.zuugle.at/tour/85973/wien is not working. This is ypour task to create a new route, which works and shows the same result as https://www2.zuugle.at/tour?id=85973&city=wien

**Comment by uzair-shakeel** [comment]
Ohh Okay, Gotcha!!
