### ISSUE TITLE
Height of map relative to screen

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#374]
The height of the map should be relative to the screen height. On mobile and on desktop. I would wish, that the frontend is determining the height of the screen. One it knows that, it deducts the height of the header. Then you take 80% (?) of what is left for the map.

Figma mobile: https://www.figma.com/proto/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?node-id=34-6220&starting-point-node-id=28%3A1001

Figma Desktop: https://www.figma.com/proto/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?node-id=330-12679&t=jYzzcAoyskAfiSoq-0&scaling=scale-down&content-scaling=fixed&page-id=110%3A5678&starting-point-node-id=110%3A5679

**Comment by Falsal** [comment]
completed

**Comment by Falsal** [comment]
Changes requested on the 15th July Meeting:

Desktop:
fix the top and bottom of the "main" screen and the rest should be taken up by the map.
Remove the white space between result and Card container

Mobile:
As per image 

![Image](https://github.com/user-attachments/assets/63bfedab-5c68-4c5d-b92c-ccee00074448)

**Comment by Falsal** [comment]
Currently we have this for desktop view:

1) with map being on



![Image](https://github.com/user-attachments/assets/9328b538-302a-4291-a804-8862e323e721)


2) with only card container on


![Image](https://github.com/user-attachments/assets/04145e80-22e0-4c0b-b603-43ebe4c9d29d)



and for mobile :
1) with map on
![Image](https://github.com/user-attachments/assets/c7cb6a6e-6e57-4c58-b52e-b041dad43f88)

2) with only card container 


![Image](https://github.com/user-attachments/assets/cdb15bcf-d72e-43fe-bc53-55773d0d51dc)




Note:
drawback the cluster sizes have changed back to standard

**Comment by Falsal** [comment]
The cluster issue mentioned above is fixed now.
The height of map is minimised to allow for part of the first row of tour cards to show
here is what the mobile looks like now :


![Image](https://github.com/user-attachments/assets/6b224aeb-2ce7-4e05-965f-e7d914d007f5)

As well as the desktop 



![Image](https://github.com/user-attachments/assets/e2479a29-5005-455e-a59c-1f4b57dffae4)

**Comment by martinheppner** [comment]
Tested it. Looks good!
