### ISSUE TITLE
URL parameter City is not respected

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#375]
I just clicked in an email, someone send to me, on https://www.zuugle.at/tour?id=9575&city=wien 
The city is given there. Unfortunately the page is ignoring the city - see screenshot. In the itinerary it is used.

Expected behaviour: Use the city in the Heimatbahnhof selection field.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/23c5f1c2-d798-4a05-af50-b75e6b3dae75)

**Comment by Falsal** [comment]
done
