### ISSUE TITLE
Design country switch button

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#39]
Design the left top button including the symbol (which you can export from Figma):

Figma Design of the left top button for country change and link to 3 pages: https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0
![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/16c5e276-1e94-4fcd-a1a6-82d13af76f33)

The 3 links to the pages are:
Über Zuugle: https://www.bahnzumberg.at/
Impressum: https://www.zuugle.at/imprint
Datenschutz: https://www.zuugle.at/privacy

![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/428e4eaa-786f-463b-976a-f15e651b8460)

**Comment by martinheppner** [comment]
Duplicate of #17

**Comment by Falsal** [comment]
pending changes to push made on the 4th/july:
1. the position of button on the overlay is not exactly matching the position of the button on the actual button.
2. clicking outside the overlay does not remove it

**Comment by Falsal** [comment]
completed design.

Pending, create functionality

**Comment by Falsal** [comment]
Current design look is attached.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/86ee571a-f438-4217-bbb8-1776b577b163)

**Comment by Falsal** [comment]
Pending:

language selector:  
the arrow that appears on the dropdown, actually switches to the domain instead it should be closing the dropdown.
also the curser shape or curser design should remain as it was (a hand pointing finger) .

**Comment by Falsal** [comment]
Pending:
the curser shape or curser design should remain as it was (a hand pointing finger)
