### ISSUE TITLE
Consolidate use of SVG logos

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#392]
Provider logos are used at two different locations at the moment. This doesn't make sense, therefore we consolidate them into one place. It should only use **\src\icons\svg\provider**

1. In ProviderLogo.js are not all new logos inserted. They have to be added.
2. If a logo is not available for a provider, the logo_fallback.svg should be used
3. When TourCard.js is working with the new path, the directory \public\logos has to be removed / deleted

**\public\logos** used in TourCard.js
![Image](https://github.com/user-attachments/assets/8229ffc7-01f1-411e-856a-47426f78cddb)

**\src\icons\svg\provider** used in DetailReworked.js
![Image](https://github.com/user-attachments/assets/f8a61b84-2032-4827-8358-07b80b136f25)

**Comment by Falsal** [comment]
Changes in : 
webpack.config _prod : add config line
copy provider folder ( icons/svg/provider) into a folder (icons/provider) in the build file structure, this new path to be used for provider logos in tour cards and in popup cards.
inside tour card and popup card re-write the path.

**Comment by Falsal** [comment]
Missing is : removal of folder "logos" in build
