### ISSUE TITLE
Loading order of first page

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#396]
![Image](https://github.com/user-attachments/assets/d3b52a74-c975-41d7-be72-edeb0ba3ced5)

**Comment by Falsal** [comment]
completed

**Comment by Falsal** [comment]
image is still not number 2, just noticed it didnt change order in Network at 2G, will do fix it then close.

**Comment by Falsal** [comment]
completed on dev, please test
