### ISSUE TITLE
Enhance Matomo tracking

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#4]
Matomo is already in place, but it tracks too little. We want the full logging, ideally without the need to set a cookie. If it is absolutely necessary to set a cookie, we will habe to introduce a cookie consent as well.

Production ID (9) should be used only on production, in all other cases use the Test project ID (11).

Matomo Production ID = 9
Matomo Test  ID = 11

**Comment by martinheppner** [comment]
Update: Gerade bemerkt, dass seit dem 19.3.2023 das Tracking kaputt ist. An dem Tag haben wir das letzte Update auf die Produktion gebracht. Dass es mir erst jetzt auffällt, ist natürlich auch nicht super, ist aber leider so.

Wenn möglich wäre es schön, wenn wir das als Quick Patch auf die Produktion bringen könnten und am aktuellen Entwicklungsbranch vorbei gehen könnten?

![Image](https://user-images.githubusercontent.com/105971399/235060551-ffcbe18e-1976-4c7c-906a-69fee51450ac.jpg)

**Comment by martinheppner** [comment]
Einen kleinen Hinweis hat mir gegeben, dass der Matomo Code auskommentiert ist. :-(

**Comment by tobHai** [comment]
Änderung in #5 sollten den alten Zustand wiederherstellen

**Comment by martinheppner** [comment]
Habe gerade beim Einrichten einer neuen Webseite, diesen Link gefunden: https://developer.matomo.org/guides/spa-tracking

**Comment by tobHai** [comment]
@martinheppner sollen wir weiterhin von "basis-new-uix" wegbranchen? 
Oder gibt es mittlerweile eine sinnvollere Alternative?

**Comment by martinheppner** [comment]
Der aktuell letzte Branch ist "basis-new-uix-tour-detail"

**Comment by martinheppner** [comment]
Hi, danke für das Einchecken des Matomo Codes! Gebt ihr mir bitte Bescheid, wenn wir es in den Development Branch (dev-drop-slovenia)  mergen sollen? Danke!

**Comment by tobHai** [comment]
@martinheppner für mich sieht es so aus als würde auf www2.zuugle.at Matomo aufgerufen werden jedoch **nicht** mit der ID der Testinstanz sonder mit der ID der Produktionsinstanz.
Ich gehe mal davon aus, dass die UAT Umgebung ebenfalls die Umgebungsvariable NODE_ENV auf "production" gesetzt ist und daher ID 9 verwendet wird.

**Comment by martinheppner** [comment]
Ja, das ist eine Erklärung. Allerdings kann ich auf der produktiven Umgebung von Matomo auch keine Aufrufe finden. Wir haben bisher immer den URL abgefragt, weil das mit dem der Umgebungsvariable nicht so gut funktioniert hat.

**Comment by tobHai** [comment]
Lokal klappt es: 
![Untitled](https://github.com/bahnzumberg/zuugle-suchseite/assets/37791246/4f917f3f-58c0-40e2-8e97-2379395bfc1f)

Kann es sein, dass die produktive Matomo Instanz keine Anfragen von anderen Domains zulässt (was natürlich Sinn macht) ?
Soll ich im Code noch die Abfrage der Umgebungsvariable anpassen?

**Comment by martinheppner** [comment]
Bei der produktiven Version ist es sicher so eingestellt. Die Testversion habe ich eigentlich so konfiguriert, dass sie alles akzeptiert.
Ich bin jetzt überfragt wegen der Umgebungsvariable. Was meinst du?

**Comment by martinheppner** [comment]
Wann soll ich den Branch in den dev-drop-slovenia mergen?

**Comment by tobHai** [comment]
Bezüglich Umgebungsvariable:
![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/37791246/9dde6e75-4164-41af-9c58-51bd2411430b)

Derzeit frage ich diese ab um zu unterscheiden, ob die ID der Matomo Prod Instanz oder die, der Testinstanz verwendet werden soll.
Du hast oben erwähnt: _Wir haben bisher immer den URL abgefragt_, daher wollte ich wissen, ob ich diese Prüfung ebenfalls adaptiert soll.

Bezüglich merge: wäre noch super, wenn jemand noch einen Blick auf die Änderungen werfen könnte bzw. Änderungen einmal auschecken und testen könnte :)

**Comment by martinheppner** [comment]
Die Abfrage "process.env.NODE_ENV === "production" teilt dir nur mit, ob du auf Produktion/UAT bist, oder auf DEV. Die Unterscheidung Produktion oder UAT machen wir nicht mittels dieser Variable. 

Die Idee dahinter war, dass UAT ganz gleich wie PROD funktionieren soll. 
Der Nachteil ist natürlich in einem Fall wie dem vorliegenden sichtbar: Man kann nicht unterschiedlich auf PROD und UAT agieren. Dazu müsste man den aufrufenden URL abfragen und auf "www." und "www2." testen.

**Comment by FALBZB** [comment]
Must revert back matomo code after the latest merge action!
