### ISSUE TITLE
Design language change button

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#40]
Design language change button in the top right corner on all pages to match the design on figma (https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0) on desktop and mobile devcices.

![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/531a7561-1334-4f06-861e-7cb498c6d735)

![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/734e1de7-b571-47b0-8ead-1a624fb075a2)

**Comment by Falsal** [comment]
Pending issues after the push on the 4th July.
1. font color is not persistent after the selection
2. clicking outside the modal/overlay does not remove it
3. selecting a different language does not change menu language as was the case.

**Comment by Falsal** [comment]
Pending issues after the push on the 5th July.

Language functionality; retain original functionality (actual change of menu language)

**Comment by Falsal** [comment]
Pending issues after the 6th July:
position of the X delete button for the removal of dropdown overlay is not exactly same position for the button itself.
