### ISSUE TITLE
Detailpage broken when first time visitor has not selected a city

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#403]
This is a severe bug, as nearly all new visitors will not have selected a city.

If they enter - e.-g. www.zuugle.it for the first time - so no city set! - and click on a tour to see the detailinformation, the result page is completely broken. Such a visitor will close the page and not return. Therefore this bug has highest priority.

![Image](https://github.com/user-attachments/assets/7b76c0c0-28cd-42c1-bde3-eb19b841fe89)

Can we show all the data - just not the itinerary. In the blue field of itinerary we put an alphabetical list of cities of this country. Above a message, which says: "Please select a city, to see the itinerary."

**Comment by martinheppner** [comment]
Actually this issue consists of four topics:

- [ ] Distorted webpage. The page should show the data of the hike, even if no city is given.
- [ ] List of all cities of a country is already in existance at the "Heimatbahnhof" selection
- [ ] In the box of the itinerary a list of the cities, ordered alphabetically. Clicking on one, sets the city and reloads the page to show details of page with itinerary.
- [ ] If there is no connection to this tour, from the newly selected city, the itinerary box is empty, telling the visitor, that there are no connections available (this functionality is already implemented)

**Comment by martinheppner** [comment]
API is now handling all three usecases: 

1. valid tour with city
2. invalid tour with city (which actually means: tour without current connections)
3. valid tour with no connection from selected city (returns invalid as well)

Tour "Wanderung durch die Tscheppaschlucht" http://localhost:3000/tour/387/no-city (first time visit) shows usecase 3, when "wien" is selected.

**Comment by Falsal** [comment]
@martinheppner  : So now when i go to this link :  http://localhost:3000/tour/387/no-city this is fine i get this :


![Image](https://github.com/user-attachments/assets/eabf7338-794b-4bdb-9f2c-64885281cc4f)



But when I replace no-city with wien , i get a broken page : 


![Image](https://github.com/user-attachments/assets/80652ce1-5819-4cf9-b110-e118b9538ebb)

**Comment by martinheppner** [comment]
fixed
