### ISSUE TITLE
Design search bar on all pages desktop/mobil

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#41]
The search bar is working as it should at the moment. The design has to be adapted on desktop and mobil version to match the figma design (https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0)

![image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/ac7d7a36-77d9-4dde-a91d-935c02c36bc2)

**Comment by Falsal** [comment]
The "Main.js" view (listing all tours) 
1. check the dimensions on figma for the menubar (height of the bar)
2. No tours appear below the bar.

**Comment by Falsal** [comment]
pending issues after the push on 5th July:

1. position of the seach bar: almost done/ see attached screenshot
2. width of input area inside the search fields: pending

Main.js:
1. No tours appear below the bar. / need

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/70447836/cace87f8-f848-427e-a8b0-4f7ebbd90733)

**Comment by Falsal** [comment]
Pending after push of 6th June:

position of the seach bar: almost done/ see attached screenshot
width of input area inside the search fields: pending

**Comment by Falsal** [comment]
Functionality should be moved to another issue.

**Comment by Falsal** [comment]
I moved the functionality to #55 with myself FALSAL assigned to it.

**Comment by Falsal** [comment]
The design on the MOBILE is not done.

**Comment by martinheppner** [comment]
Searchbar on Desktop like defined on https://www.figma.com/proto/1PpoRQVVo1C59QnfODpNv1/zuugle-redesign-2023-v2.0?node-id=110-5679&starting-point-node-id=110%3A5679 

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/a31e26f0-ded5-4f4c-a79e-26ade7ae7281)


Searchbar design on mobile (without the wizard like functionality): https://www.figma.com/proto/1PpoRQVVo1C59QnfODpNv1/zuugle-redesign-2023-v2.0?node-id=28-1001&starting-point-node-id=28%3A1001
