### ISSUE TITLE
Number of map markers does not match the tour results figure anymore

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#415]
The results (number of tours ) below the map stopped matching the number of markers on map.
Possible causes:
-  caused by one of the updated libraries ? update done on a few libraries on both api and suchseite.
- this could also be a side effect of our changes yesterday / today (10th)
- some residual code after the merging of dev branch

Note: upon a quick check, when I scroll the card container below, the result figure matches  markers , unless the number of markers is a low number like a 7 . 

![Image](https://github.com/user-attachments/assets/34e4087b-ed84-4c8d-a837-3f6fcb99aaa9)

**Comment by martinheppner** [comment]
Please keep in mind, that the performance optimization (https://github.com/bahnzumberg/zuugle-suchseite/issues/182) might conflict with your topic here. My latest info is, that tomorow (30th of August) the next deployment is to be expected.
