### ISSUE TITLE
Calendar day switch crashes on days with no connection

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#425]
In this link : https://www.zuugle.at/tour/337/feldkirch/?datum=2024-08-21
we have a connection on the day where connections are there we are able to see the page, but when we attempt to select another day on the calendar the page crashes. (on a day when no connection is available)

Error message :
"Rendered fewer hooks than expected. This may be caused by an accidental early return statement."

Related files:
DetailReworked , Itinerary, ItineraryCalendar, ItineraryTourTimeLineContainer

![Image](https://github.com/user-attachments/assets/a9a71475-63bd-4eb0-9fce-69f8b9c08ec3)

**Comment by martinheppner** [comment]
Duplicates https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=75175944

- The pages crashes only if days with and without connection mix. 
- A tour with all days with connection does not crash
- A tour with no connections at all, does not show itinerary
