### ISSUE TITLE
Cleanup: Remove use of outdated columns

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#44]
Use of the columns "internal_status" and "connection_url", "return_url" in table **fahrplan** should be removed. 
In table **tours** the use of column "children" and "internal_status" should be removed. Is "publishing_date" used?

The follow up issue in the backend is https://github.com/orgs/bahnzumberg/projects/2/views/1?pane=issue&itemId=31349571

**Comment by Falsal** [comment]
"publishing_date" , "internal_status", "connection_url" are not in suchseite.
children as a column has been commented out and will be removed in the clean up process .
