### ISSUE TITLE
Search / City - Symbols & Text

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#442]
If **no city** is given, t("start.heimatbahnhof") is shown, instead of the city. The search symbol is left, the railway symbol is right.

![Image](https://github.com/user-attachments/assets/72ae273c-fe10-440a-8305-06932babb154)

If a **city is given**, the word before the city should be shown as the variable "t("start.ab_heimatbahnhof") then a space and then the city. This variable is translated to all 5 languages and is returning for German "ab", for English "from" and so on.

![Image](https://github.com/user-attachments/assets/3fa8732d-e014-444e-9544-3290cedff704)

On the mobile part the same.

**Comment by Falsal** [comment]
done
