### ISSUE TITLE
Replace "Did not find anything?"

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#450]
When opening https://www.zuugle.at/search?city=wr-neustadt and trying to change the city, the window below appears.

This text (including the "comments") should be replaced by the already prepared translation "details.bitte_stadt_waehlen"

![Image](https://github.com/user-attachments/assets/0c0b6a09-f7ac-406f-8eb6-d63e70008227)

**Comment by Falsal** [comment]
The first line of  text is not there
As far as I could check; the second is not in the figma anywhere, I remember it was here in old design.
