### ISSUE TITLE
Uncaught error: Map container is already initialized

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#454]
Mobile version, Samsung handy

Link: https://www.zuugle.it/search?city=trento&map=true&filter=%7B%22coordinatesSouthWest%22%3A%7B%22lat%22%3A45.836454050187726%2C%22lng%22%3A5.350341796875001%7D%2C%22coordinatesNorthEast%22%3A%7B%22lat%22%3A49.489538473066496%2C%22lng%22%3A21.368408203125004%7D%2C%22search%22%3Anull%7D

![Image](https://github.com/user-attachments/assets/18e705a9-3efb-4770-aa75-ec5c8998b632)

**Comment by Falsal** [comment]
@martinheppner : 
I am working on issue #415 which is also on the map so i stopped to I research this issue #454 : so for a  solid solution I will have to add a useEffect to remove map instance when map is being re-rendered, will do it by end of this weekend.
