### ISSUE TITLE
Fix code scanning alert - Missing rate limiting

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#47]
Tracking issue for:
- [ ] https://github.com/bahnzumberg/zuugle-suchseite/security/code-scanning/2

**Comment by martinheppner** [comment]
https://codeql.github.com/codeql-query-help/javascript/js-missing-rate-limiting/

**Comment by Falsal** [comment]
@martinheppner : added the package and relevant code in the server file (src/server/server), please check the current value of allowed calls per window (at 100 per 15 minutes), if you need to change it inform me, so I would adjust.

**Comment by Falsal** [comment]
please checkout to my branch to see the changes:  https://github.com/bahnzumberg/zuugle-suchseite/tree/dev-clean-up-fal/server

**Comment by martinheppner** [comment]
Can we please test first two scenarios on UAT?

1. What happens if the rate is reached? For this we have to lower the rate - let's say to one request per minute?
2. Do we have in our setup a proxy before our server? We can determine this using this howto page https://express-rate-limit.mintlify.app/guides/troubleshooting-proxy-issues

**Comment by Falsal** [comment]
i. on UAT : nothing changed when I switched the allowed number of requests per minute from 100 per 15 min to 1 per minute, meaning that the behaviour of the website, did not change and continued to allow me to make requests by clicking on different GO buttons and displaying tours.

ii. regarding the troubleshooting of proxy issues link; need to revise the documentation of express to get back on this, will do it tomorrow.

**Comment by martinheppner** [comment]
So it did not work. Hm. Unfortunate.

**Comment by Falsal** [comment]
Seems to be fixed now, If we get the alert again then please inform me.
