### ISSUE TITLE
Search suggestions do not appear when on focus

### ISSUE THREAD

**Issue by Falsal** [bahnzumberg/zuugle-suchseite#480]
This is part of the list of bugs found by FAL on the 10th Sept

**Comment by martinheppner** [comment]
When I start typing in the search field, there should be a list of suggestions. Now there are none:

![Image](https://github.com/user-attachments/assets/02801011-61bf-4da5-bb11-a6eace25932b)

**Comment by martinheppner** [comment]
This is only true, when no city is selected. This is actually how we designed it so far. But of course it might make sense to return suggestions even if there is no city set. Has to be analyzed.
