### ISSUE TITLE
No GPX download for specific providers

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#65]
Some providers insist, that visitors must not download their GPX track. There has to be a table, which must be fetched from the remote DB via sync.js and when the GPX button is drawn, it is first checked if this provider forbids to show the button. Only if not listed in the table, the button will be shown. The provider https://mapzs.pzs.si/home/trails is such a provider.

**Comment by FALBZB** [comment]
This is a permanent solution for issue https://github.com/bahnzumberg/zuugle-suchseite/issues/72 which is in milestone dev-drop-slovenia,
Basically , create an action call to the backend table "provider" in tourActions.js where a provider name is given and the call will retrieve either a "y" or a "n" value . We use it then in the Details page to possibly mute the button "downloadGpx" and "downloadPdf"

**Comment by martinheppner** [comment]
@FALBZB please adapt your comment above. This feature is only relevant for the GPX download, but not for the PDF button!

**Comment by Falsal** [comment]
completed
