### ISSUE TITLE
Amount of results missing

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#68]
Current:

![Image](https://user-images.githubusercontent.com/105971399/256296758-c5bfe741-dbd0-483d-a523-cbd7a107fea8.png)

Target:

![Image](https://user-images.githubusercontent.com/105971399/256296867-d30c1b0a-5797-4d8f-bdda-bf67e03b896a.png)

**Comment by FALBZB** [comment]
Done
