### ISSUE TITLE
Download GPX feature disabled for specific providers

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#72]
Specific providers do not want, that their GPX tracks can be downloaded. We introduce the possibility not to let the GPX downloaded for the providers, which are marked in the view vw_provider_to_search, when in the allow_gpx_download column there is a 'N'.

mapzssi is such a provider. They understand, that deactivating the GPX download feature will disable the part Zuugle calculated at the beginning and at the end of the track (from the last bus/train station and to the bus/train station), which will make it more difficult for the visitor.

**Comment by FALBZB** [comment]
This issue will be for a hard-coded solution due to the time-squeeze of the dev-drop-slovemia project.There will be another issue for a permanent solution using a backend call.

**Comment by FALBZB** [comment]
completed for one hard-coded provider name
