### ISSUE TITLE
Bug: URLs not correct über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#75]
Von: Martin Heppner 
In the file index.js in Suchseite the domains are not correct. They all are
missing the www.
Example: https://www.zuugle.at

[image: image.png]

-- 

*Verein Bahn zum Berg*

ZVR: 1112324997

w: www.bahn-zum-berg.at / www.bahn-zum-berg.de

m: martin.heppner@bahn-zum-berg.at <martin@bahn-zum-berg.at>

t: +4366473662152

book me: https://calendar.app.google/giye2D3VYRvY7ZYT7

Attachments (1): https://zapier.com/engine/hydrate/11523678/.eJxNkcmSokAURf8l19KBDJq4w3ICBVNEBTs6iCQZ1WTKRCwq6t-Lru6O6O17996zOB-AlAWPCx7w9yoGM6CDEcgLxnFB4iCPwEyWVChOZGUESMt4SVsWN9-P8ViV5MkUjgAmpGyHiX_XsSKLI5Dk8SMKCkx_z2LOMcnoAGID4N7hJmVg9gFozBhO_5DAGGqhFBIYhVEIyTQckv_3Zj8_wHdOt9e3yAzMO-66vexo6NZYkE1fMFMcda5XL69zme-21boTEqahdhodFgwdIc5cn-Zsq_uh2aiKMKnKrF6458zJz1ksDNCVFSNtV8LQfW6c-e1d9gyrs4Wjci-JwfDbPltg236l6FAu2KNQoK2UtZ9QzRX7Smx4H_YiUk6-ye9Gv9k4XlW-seVU05OTcbi-22pUJ06rUpPRi7zfvqQm8sZ61BpHi5wC8cyaCjX8mkqyaS5vnRJj4XG7p2lR7faXbdKsnaJf4Y4K7n7-vB4WpLHQxePhlCFBWsIHUnHWXTZQf1BNDh1ieA59eNEK7ZZVAscePsqy0eLUDws1KppVlPe5ObfWqrtdIgy51OvcR0FKRAGHDjVTt5KtU9LUb0-9draCurZqdqvLu8_sKj_X8511InGN3MHVX9U5HYT-qIoUfP76_PwCIqjMLQ:1qQvr5:hK8uhIWiP_tx9pw6EN4sCkva4b0/

**Comment by FALBZB** [comment]
Done last week!
