### ISSUE TITLE
Searchfield not translated on mobile über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#77]
Von: Martin Heppner 
I selected zuugle.si and Slovenian language. The search field is not
translated on my mobile - see screenshot. On desktop it is translated.

Attachments (1): https://zapier.com/engine/hydrate/11523678/.eJxNkduSojAURf8lzzKVEBDwDaEREWhp2kaZmqKQe5SgCRe1q_99nFvVvJ6z914P6xNkHe0L2if9_VKABdDBDDSU9ynNiqTJwQKLsgrnWJqBbOB91w68YL8fCMkinivqDKRZ1g3PiX9XJGE4A2VTnPOEpu2v2bTv06xunyD-BJymlFUcLD5BW3CeVn9IAKnaMYNqmuUlRBnCz-T_vcX3T_A7p_srkjuCHbYiXGrm7kMhSbTP6uOG2JqrhFVymF_FQb0ZqVceXBRkNSZQ9Pvg2mzc6sWlnsaW6x0SLhIKpzIXouJVxsbaLigSUmn_Wk-i5H5Q2unMYrEn772PdLoF3DQ6Fb9j59w_bnWu9b4eO6aq2InD9rtRoALJLXdl628H3pJBKoTI3LmOgMIoPnH5pZkbWzgMAofacYois76LNwevrL7ZwOBC8Gbtm6xItrhDte2-D3t8rrC4JP54vFEjqN9CJ76ORJ6z9UhNczIt47FSGnpQpzsZ9i8PuL0dDHE6B8OJdeNr6Cv3dbIhteckTlLC0XhTyrjRnpJqa7lzrkgPZDI-3FbWsG7scv9c45IbFvPiS28FvgLZVto0otSgZSpfQ_XUzddRNtqnu2dUuemuYhKduEa2T1d_VYcZKwrK665PRChiqEKcIEXUIEyMmnVt8Y1cKvD14-vrJ87Szpo:1qRaWz:PSZi3E69yYug6aqnWL_RRNjfqmY/

**Comment by FALBZB** [comment]
weird, because on my www2.zuugle.si i get the following attached effect, menu language is sl

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/0140aff5-05b3-44bd-870f-949a7f8a893c)

**Comment by martinheppner** [comment]
So maybe fixed, in the meanwhile? I am closing the ticket.
