### ISSUE TITLE
Correct country at bottom of startpage

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#84]
The country shown at the bottom of the startpage seems to be hardcoded Austria. But it has to change to the currently selected country, determined by the domain. In the screenshot .si is selected, but Austria is shown. Should be "Slovenija".

![Image](https://user-images.githubusercontent.com/105971399/260921199-a436a05e-45bb-4ab0-99d9-e4823157300d.png)

**Comment by FALBZB** [comment]
fixed it : see commit c92a782: fix getCountryKey, issueCorrect country at bottom of startpage #84

**Comment by FALBZB** [comment]
Another related issue should be created to design the 404 page
