### ISSUE TITLE
Logo für mapzzsi

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#88]

**Comment by martinheppner** [comment]
@FALBZB where do I find this logos please?


![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/6907b776-3ef9-4ba9-8321-bcaebf1ff1b4)

**Comment by FALBZB** [comment]
you will find it in *src/icons/svg*
but the logo has to be included in file : *ProviderLogo.js.         (*this
file is in src/icons)

**Comment by martinheppner** [comment]
Created, added and uploaded Logo to GitHub for provider mapzssi
