### ISSUE TITLE
3 weitere Rückreisemöglichkeiten über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#89]
Von: Martin Heppner 
Die Anzeige ist hardcoded und nimmt keine Rücksicht darauf wie viele
Rückreiseoptionen wirklich existieren. Statt immer die Zahl "3" anzuzeigen,
sollte dort die echte Anzahl noch verfügbarer Rücksreiseoptionen stehen.

[image: image.png]

-- 

*Verein Bahn zum Berg*

ZVR: 1112324997

w: www.bahn-zum-berg.at / www.bahn-zum-berg.de

m: martin.heppner@bahn-zum-berg.at <martin@bahn-zum-berg.at>

t: +4366473662152

book me: https://calendar.app.google/giye2D3VYRvY7ZYT7

Attachments (1): https://zapier.com/engine/hydrate/11523678/.eJxNkcmSokAURf8l19rBPLijRFApmcoJOzoykiSlkGQQEhEN_73o6u6I3t533z2L8wS4KhkpGWRDTcAMGGACsrJlqMQEZgmYiYKscYooTQDuWlYVXUua7wPPy4KoqNoEIIyrbpz4l_KSyE3AOSM0gSUqfs8ixhD-LEZQOwLyHjVpC2ZPUJC2RekfEuA1xOEEc5yqIknh5bH5_9_s5xN89wzXviRrDZPD-zV1nDrxL8Z54xWRsH94sbAX1tDZWLcj3m1OQ702TTvFoV4g37_nx5XWBN5J0ujdkphSlemCz243NaORcblf7ujUbZzIi6C0c3e6pduGgXrTvC6neQW3KFDCpa_HtDaGnClYusSpNQZC8c6H1-n1kW-pp0J9c-izT66cM2e7J1F6zYttENrRsLMeIhS8kCa1px_I2pkmSAuyDtchnc4fetq1ZRyn0_l5ZX5EeyN0ZGEIbFd-UHgnHC2wJPMxPOXJm_yxbHEqNJyvp-aCkpw7LXSVxAGZhvWBv8kBrJzV8jKWfST4SkcUG2kEoasrir2bUQaP2DId0m5NCKlr9QM8P_ohdv2waejdYIet3ywcdsJzI79ZtqPHOlUrrxv6N9TMS0VZu2LrfQ6r5OD4o6u_qrNiFPqjLlPw-vV6fQGszsqF:1qXHGQ:SVgiH6wlAVWdtruQE8H2-4QMMb0/

**Comment by FALBZB** [comment]
done
