### ISSUE TITLE
Sharing aging link at the detail page of one tour

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#9]
**Desktop:** The visitors can share the link via social media or e-mail. After the users clicks on the button, a selection of available options apears, from which he can select one. Facebook, Instragam, E-Mail should be covered.

**Mobile:**  Ideally the standard sharing options on the mobile (iOS and Android) should be available and used.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/537db811-ab22-4a13-9ef3-eb11d14de58e)

**Comment by martinheppner** [comment]
Version 3: Mobile & Desktop: https://www.figma.com/file/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?type=design&node-id=0-1&t=g3UdMU8w26zmTY3s-0

**Comment by martinheppner** [comment]
Sharing Link is only created, when the user clicked on the sharing button.

**Comment by Cleatuer** [comment]
Should a completely new link be created every time we click the share button, or can we re-use existing ones, if they fit the selected date and city?

**Comment by Cleatuer** [comment]
We investigated a bit, and it seems to be that sharing on Instagram is not really supported for web-applications, also see: 
![MicrosoftTeams-image (14)](https://github.com/bahnzumberg/zuugle-suchseite/assets/22658924/b070daec-5907-44b0-a56d-21d9ec54dd43)


However, we found a promising **npm package** that supports plenty of other options and were wondering, if we were allowed to use that for Zuugle. You can also choose an alternative for Instagram from all the other options in the list:
https://www.npmjs.com/package/react-share

**Comment by Falsal** [comment]
@Cleatuer @martinheppner  i dont know it , but i don't see why not to use it , seems that it is well maintained lib. Just ask you to first research if there are any major recent complaints from the community of users.

**Comment by Falsal** [comment]
https://github.com/bahnzumberg/zuugle-suchseite/issues/9#issuecomment-1631950732 
My guess would be create a new one, that would avoid a new search to look for the existing one. This is assuming that the number of shares in the system stays within reasonable numbers.  I may be missing other considerations.
@martinheppner : what do you say?

**Comment by martinheppner** [comment]
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/6f168dca-7f2a-4103-92ad-7dd9bee141da)
