### ISSUE TITLE
Delete search term button missing

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#90]
Von: Bernhard Spitzer 
Hallo Martin

Wenn ich meinen Heimat Bahnhof eingebe und einen Suchbegriff z.B. Alpenverein so wird das Ergebnis wie gewünscht gefiltert. Wenn ich den Suchbegriff aber lösche und keinen weiteren Suchbegriff mehr eingeben möchte (also alles anzeigen lassen will) so geht das nicht, denn der alte Suchbegriff ist immer noch aktiv…

Mit freundlichen Grüßen / Best regards

Bernhard Spitzer
Attachments (0):

**Comment by FALBZB** [comment]
@martinheppner  : not withstanding the behaviour of the input field in the results (Main) page -which is being done by the externals as part of the design work- what is described above does not seem to be repeating with my local app setup. see the video below:

https://www.loom.com/share/c969aca734a44171804584946c364b3a?sid=9f151649-a930-44bb-8219-6a3244d3f896

**Comment by FALBZB** [comment]
I made a video , to show the current behaviour:

https://www.loom.com/share/c969aca734a44171804584946c364b3a?sid=585545e2-23c1-4bef-a01b-2f0112b66d88

**Comment by FALBZB** [comment]
This is a design issue of the X button, part of job taken by the externals
