### ISSUE TITLE
Filter on "Steiner Alpen" not working

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#95]
Original (9) of #93 

Wenn man "Ljubljana" als Startpunkt wählt und dann auf die Touren in den
"Steiner Alpen" filtert, bekommt man "0 Ergebnisse". Das ist erstaunlich,
denn ohne Filter sehe ich drei Touren, zwei überlappende Talwanderungen und
einen Spaziergang mit 1,8 km und 108 HM. Da ist keine Bergtour dabei. Und
das obwohl die Steiner Alpen von Ljubljana öffentlich gut erreichbar sind
und die "Nummer 1"-Bergdestination von Ljubljana aus darstellen
(vergleichbar mit Schneeberg und Rax von Wien aus) und es dort auch ähnlich
viele attraktive Touren gibt. Das schränkt die Brauchbarkeit der aktuellen
Version für Ljubljana als Ausgangspunkt mE sehr stark ein.

**Comment by FALBZB** [comment]
Lets look at these together

**Comment by martinheppner** [comment]
Sorry, I have renamed the "Steiner Alpen" to 'Kamniške Alpe', which is the correct slovenian name, as they are situated in Slovenija.

**Comment by martinheppner** [comment]
Can not be reproduced
