### ISSUE TITLE
Searching bar Überlappung über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#97]
Von: Veronika Schöll 
Mobile Version (nur meine Anzeige?) Suchleiste : Startort ausgewählt - Go -
Ergebnisanzahl und Ort überlappend angeordnet.
-- 

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/3da3034c-931f-4055-adb5-94f68cf52d22)

**Comment by FALBZB** [comment]
This should automatically be cured by the work the external guys currently do in the design work

**Comment by FALBZB** [comment]
Done : see sceenshot

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/3fc3c401-7ccd-4f4a-9e21-d02075b104ed)
