### ISSUE TITLE
Schwierigkeitsgrad verwirrend über test@zuugle.at

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#99]
Von: Veronika Schöll 
Hier steht Mittel und leicht

https://www2.zuugle.at/tour?id=5743&city=bischofshofen

-- 

*Verein Bahn zum Berg*

*Zuuglest du schon, oder fährst du noch?*

ZVR: 1112324997

w: www.bahn-zum-berg.at / www.bahn-zum-berg.de

m: veronika.schoell@bahn-zum-berg.at

t: +436645345626

Attachments (1): https://zapier.com/engine/hydrate/11523678/.eJxNkcmSmkAAht-lz06q2Vr0xggCIorAuKVSVEM3i9BApAXUmnePmSRVuf7bd_ifIGlqTmse8XtLwRxoYAKKuuO4TmhUEDCXREWFSJInILl1vGG3jl6_DEFQRAlN1QnASdLcXhP_VEGW4ASkBa1IVGP2exZzjpOcvUDdC1AO-Jp1YP4EjHYdzv6QgKBiAdGEUkUVJBmRV_L_3vz7E3zltI15ISvVDPVer3M79G8DcdXjwRiXyIWqS-N0qgfl6azctKsGeVpt7lvjY3DsVCrzKsruQ17ts4QtVdfwA-UYCHFkaGh3Vt2Ht9KUx3F9kLFuScW7FxRVP6ytzQDh3vDU00hiW67Sgxz4F-SLFZKrdicqJBMO57II0jdo3O2dlzQ-KSGKrppYGlYiD2rXP9iZ9Pm1GJPr8h3l-gwyc2RNuvFT7gs3ljWNs_a8UzA6J2vgzu7BtoKdr9V81bTrwIR6ZJMOz5C1JTgbHaxfI5GVyp5etqJks9Qm5GNhocN73Y3TBZSbM6d-1stsbHMixpt7E6Jdyc311H5odRWXnLTeWzo7uqzH6k-vMYrLhYatCem-GbV4ucAr3pH7PmrjqEbdB7emXAkV1w-Ns7OLu6R3JOjJizJ8ffX3ats1IxHC2bdLm4HPH5-fvwCrPsqN:1qXz6m:VCxw_ZG0FLBYtcFeAtWykWkSUWE/

**Comment by spheppner** [comment]
In Crunchy both difficulties (orig and ours) are set to easy (1, or "leicht").

**Comment by spheppner** [comment]
In our system the difficulties are mapped like:
1 -> "Leicht"
2 -> "Mittel"
3 -> "Schwer"

**Comment by FALBZB** [comment]
completed: screenshot provided

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/139218009/9cc82d2b-54fd-484f-93d0-2907398981c5)
